# Generated by Django 3.1 on 2021-11-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_export_celery', '0006_auto_20191219_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportjob',
            name='format',
            field=models.CharField(max_length=255, null=True, verbose_name='Format of file to be exported'),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='format',
            field=models.CharField(max_length=255, verbose_name='Format of file to be imported'),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='model',
            field=models.CharField(choices=[('User profile', 'User profile'), ('Company profile', 'Company profile'), ('Donor Payment Channel', 'Donor Payment Channel'), ('Interaction', 'Interaction'), ('Payments', 'Payments')], max_length=160, verbose_name='Name of model to import to'),
        ),
    ]
