# Generated by Django 2.2.18 on 2021-02-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210212_1819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='organizationposition',
            options={'verbose_name': 'Organization position', 'verbose_name_plural': 'Organization position'},
        ),
        migrations.AlterModelOptions(
            name='organizationteam',
            options={'verbose_name': 'Organization team', 'verbose_name_plural': 'Organization teams'},
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_method',
            field=models.CharField(choices=[('standard', 'Standard'), ('other_electronic', 'Other electronic'), ('by_email', "By organizer's email"), ('not_required', 'Not required'), ('full', 'Full, not anymore')], default='standard', max_length=128, verbose_name='Registration method'),
        ),
    ]
