# Generated by Django 2.2.19 on 2021-04-21 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20210415_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='organizing_associations',
        ),
        migrations.DeleteModel(
            name='OrganizingAssociation',
        ),
    ]
