# Generated by Django 2.2.20 on 2021-04-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20210421_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='gps',
        ),
        migrations.AddField(
            model_name='location',
            name='gps_latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='GPS latitude'),
        ),
        migrations.AddField(
            model_name='location',
            name='gps_longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='GPS longitude'),
        ),
    ]
