# Generated by Django 2.2.20 on 2021-04-29 16:35

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20210422_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, default=None, editable=True, help_text='Identifier of the campaign', max_length=100, null=True, populate_from='name', unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, help_text='Identifier of the event type', max_length=100, populate_from='name', unique=True, verbose_name='Slug'),
        ),
    ]
