# Generated by Django 2.2.20 on 2021-05-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20210507_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='total_participants',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Total participations'),
        ),
        migrations.AddField(
            model_name='event',
            name='total_participants_under_26',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Total participations under 26 years'),
        ),
        migrations.AddField(
            model_name='event',
            name='total_working_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Total working days'),
        ),
    ]
