# Generated by Django 2.2.24 on 2021-07-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20210521_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='comment_on_work_done',
            field=models.TextField(blank=True, default='', max_length=2000, null=True, verbose_name='Comment on work done'),
        ),
        migrations.AddField(
            model_name='event',
            name='other_work',
            field=models.TextField(blank=True, default='', max_length=2000, null=True, verbose_name='Other work'),
        ),
    ]
