# Generated by Django 2.2.20 on 2021-07-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20210719_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='public_on_web_date_from',
            field=models.DateField(blank=True, null=True, verbose_name='Public on the web date from'),
        ),
        migrations.AddField(
            model_name='event',
            name='public_on_web_date_to',
            field=models.DateField(blank=True, null=True, verbose_name='Public on the web date to'),
        ),
    ]
