# Generated by Django 2.2.20 on 2021-07-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20210729_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='basic_purpose',
            field=models.CharField(choices=[('action', 'Action'), ('petition', 'Petition'), ('camp', 'Camp'), ('opportunity', 'Opportunity')], default='action', max_length=128, verbose_name='Basic Purpose'),
        ),
    ]
