# Generated by Django 2.2.20 on 2021-07-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20210729_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='opportunity',
            field=models.CharField(blank=True, choices=[('', '---'), ('organizing_events', 'Organizing events'), ('cooperation', 'Cooperation'), ('help_the_locality', 'Help the locality')], max_length=128, verbose_name='Opportunity'),
        ),
    ]
