# Generated by Django 2.2.20 on 2021-07-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_event_opportunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='additional_question_4',
            field=models.CharField(blank=True, max_length=300, verbose_name='Additional question number 4'),
        ),
    ]
