# Generated by Django 2.2.24 on 2021-09-28 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20210902_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='administrative_unit',
        ),
    ]
