# Generated by Django 2.2.24 on 2021-12-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_remove_location_administrative_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='basic_purpose',
            field=models.CharField(choices=[('action', 'Action'), ('action-with-attendee-list', 'Action with attendee list'), ('petition', 'Petition'), ('camp', 'Camp'), ('opportunity', 'Opportunity'), ('campaign', 'Campaign')], default='action', max_length=128, verbose_name='Basic Purpose'),
        ),
    ]
