# Generated by Django 2.2.24 on 2021-12-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20211212_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='datetime_from',
            field=models.DateField(blank=True, null=True, verbose_name='Date from'),
        ),
    ]
