# Generated by Django 3.1.14 on 2022-01-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20211212_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='datetime_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date and time from'),
        ),
    ]
