# Generated by Django 3.1.14 on 2022-02-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_auto_20220117_0055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='indended_for',
            new_name='intended_for',
        ),
        migrations.AlterField(
            model_name='event',
            name='grant',
            field=models.CharField(choices=[('no_grant', 'No grant'), ('other', 'Other grant')], default='no_grant', max_length=128, verbose_name='Grant'),
        ),
    ]
