# Generated by Django 3.1.14 on 2023-03-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_remove_organizationteam_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event',
            field=models.ManyToManyField(blank=True, related_name='_event_event_+', to='events.Event', verbose_name='Event'),
        ),
        migrations.AddField(
            model_name='event',
            name='print_point_1',
            field=models.TextField(blank=True, help_text='Print point 1', null=True, verbose_name='Print point 1'),
        ),
        migrations.AddField(
            model_name='event',
            name='print_point_2',
            field=models.TextField(blank=True, help_text='Print point 2', null=True, verbose_name='Print point 2'),
        ),
        migrations.AddField(
            model_name='event',
            name='print_point_3',
            field=models.TextField(blank=True, help_text='Print point 3', null=True, verbose_name='Print point 3'),
        ),
        migrations.AddField(
            model_name='event',
            name='print_point_4',
            field=models.TextField(blank=True, help_text='Print point 4', null=True, verbose_name='Print point 4'),
        ),
        migrations.AddField(
            model_name='event',
            name='print_point_5',
            field=models.TextField(blank=True, help_text='Print point 5', null=True, verbose_name='Print point 5'),
        ),
        migrations.AddField(
            model_name='event',
            name='print_point_6',
            field=models.TextField(blank=True, help_text='Print point 6', null=True, verbose_name='Print point 6'),
        ),
        migrations.AddField(
            model_name='event',
            name='url',
            field=models.URLField(blank=True, help_text='Url address of website', null=True, verbose_name='Url address of website'),
        ),
        migrations.AddField(
            model_name='event',
            name='url1',
            field=models.URLField(blank=True, help_text='Url address of website 1', null=True, verbose_name='Url address of website 1'),
        ),
        migrations.AddField(
            model_name='event',
            name='url2',
            field=models.URLField(blank=True, help_text='Url address of website 2', null=True, verbose_name='Url address of website 2'),
        ),
        migrations.AddField(
            model_name='event',
            name='url_title',
            field=models.CharField(blank=True, help_text='Url tittle', max_length=255, null=True, verbose_name='Url tittle'),
        ),
        migrations.AddField(
            model_name='event',
            name='url_title1',
            field=models.CharField(blank=True, help_text='Url tittle 1', max_length=255, null=True, verbose_name='Url tittle 1'),
        ),
        migrations.AddField(
            model_name='event',
            name='url_title2',
            field=models.CharField(blank=True, help_text='Url tittle 2', max_length=255, null=True, verbose_name='Url tittle 2'),
        ),
        migrations.AddField(
            model_name='location',
            name='specific_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Specific name'),
        ),
    ]
