# Generated by Django 3.1.14 on 2024-04-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_auto_20240326_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='basic_purpose',
            field=models.CharField(choices=[('action', 'Action'), ('action-with-attendee-list', 'Action with attendee list'), ('petition', 'Petition'), ('camp', 'Camp'), ('opportunity', 'Opportunity'), ('campaign', 'Campaign'), ('zmj_location', 'ZMJ location')], default='action', max_length=128, verbose_name='Basic Purpose'),
        ),
    ]
