# Generated by Django 3.1.14 on 2024-04-04 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_auto_20240402_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date_from',
        ),
    ]
