# Generated by Django 3.1.14 on 2024-04-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_remove_event_date_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date to'),
        ),
    ]
