# Generated by Django 3.1.14 on 2024-04-04 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_auto_20240404_0912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date_to',
            new_name='datetime_to',
        ),
    ]
