# Generated by Django 3.1.14 on 2025-12-12 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_rename-date_to-field-to-datetime_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='activities',
            field=models.TextField(blank=True, help_text='Activities description', verbose_name='Activities'),
        ),
        migrations.AddField(
            model_name='event',
            name='space_area',
            field=models.CharField(blank=True, choices=[('xs', 'Less than 500 m²'), ('sm', '500-1000 m²'), ('md', '1000-2000 m²'), ('lg', '2000-5000 m²'), ('xl', 'More than 5000 m²')], max_length=255, null=True, verbose_name='Space area'),
        ),
        migrations.AddField(
            model_name='event',
            name='space_rent',
            field=models.BooleanField(default=False, verbose_name='Space rent'),
        ),
        migrations.AddField(
            model_name='event',
            name='space_type',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('park', 'Park'), ('sidewalk', 'Sidewalk'), ('road', 'Road'), ('yard', 'Yard')], max_length=255, null=True, verbose_name='Space type'),
        ),
    ]
