# Generated by Django 3.1.14 on 2025-12-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_auto_20251212_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='activities',
            field=models.TextField(blank=True, help_text='Activities description', null=True, verbose_name='Activities'),
        ),
        migrations.AlterField(
            model_name='event',
            name='space_area',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('xs', 'Less than 500 m²'), ('sm', '500-1000 m²'), ('md', '1000-2000 m²'), ('lg', '2000-5000 m²'), ('xl', 'More than 5000 m²')], max_length=255, null=True, verbose_name='Space area'),
        ),
    ]
