# Generated by Django 3.1.14 on 2025-12-21 21:57

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_auto_20251215_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of category', max_length=100, verbose_name='Name')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, help_text='Identifier of the category', max_length=100, populate_from='name', unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, help_text='Description of this category', max_length=3000, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.Category', verbose_name='Categories'),
        ),
    ]
