# Generated by Django 3.1.14 on 2025-12-22 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_auto_20251221_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('reminded', 'Reminded'), ('overdue', 'Overdue'), ('paid', 'Paid')], default='draft', max_length=50, verbose_name='Status')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices', verbose_name='PDF File')),
                ('invoice_number', models.CharField(blank=True, help_text='Invoice number or identifier', max_length=100, verbose_name='Invoice Number')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Invoice amount', max_digits=10, null=True, verbose_name='Amount')),
                ('due_date', models.DateField(blank=True, help_text='Payment due date', null=True, verbose_name='Due Date')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date of last change')),
                ('note', models.TextField(blank=True, help_text='Additional notes about the invoice', max_length=2000, verbose_name='Note')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='events.event', verbose_name='Event')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
            },
        ),
        migrations.CreateModel(
            name='EventChecklistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the checklist item', max_length=255, verbose_name='Name')),
                ('checked', models.BooleanField(default=False, help_text='Whether this item is completed', verbose_name='Checked')),
                ('custom', models.BooleanField(default=False, help_text='Whether this item is custom', verbose_name='Is Custom')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='events.event', verbose_name='Event')),
            ],
            options={
                'verbose_name': 'Event Checklist Item',
                'verbose_name_plural': 'Event Checklist Items',
            },
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('signed', 'Signed'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='draft', max_length=50, verbose_name='Status')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='agreements', verbose_name='PDF File')),
                ('pdf_file_signed', models.FileField(blank=True, null=True, upload_to='agreements', verbose_name='PDF File Signed')),
                ('pdf_file_completed', models.FileField(blank=True, null=True, upload_to='agreements', verbose_name='PDF File Completed')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date of last change')),
                ('note', models.TextField(blank=True, help_text='Additional notes about the agreement', max_length=2000, verbose_name='Note')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='events.event', verbose_name='Event')),
            ],
            options={
                'verbose_name': 'Agreement',
                'verbose_name_plural': 'Agreements',
            },
        ),
    ]
