#!/bin/bash
export DISABLE_COLLECTSTATIC=1
export DJANGO_SETTINGS_MODULE=project.settings.heroku
NEW_RELIC_CONFIG_FILE=newrelic.ini newrelic-admin run-program gunicorn wsgi --timeout ${GUNICORN_TIMEOUT:-"60"} --workers ${GUNICORN_WORKERS:-"2"}
