# Generated by Django 2.2.8 on 2019-12-19 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('import_export_celery', '0006_auto_20191219_0913'),
        ('aklub', '0058_auto_20191219_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrative_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aklub.AdministrativeUnit')),
                ('importjob', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='import_export_celery.ImportJob')),
            ],
        ),
        migrations.CreateModel(
            name='ExportConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrative_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aklub.AdministrativeUnit')),
                ('exportjob', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='import_export_celery.ExportJob')),
            ],
        ),
    ]
