# Generated by Django 2.2.12 on 2020-06-24 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('import_export_celery_edit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importconnector',
            name='administrative_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aklub.AdministrativeUnit'),
        ),
    ]
