# Generated by Django 2.2.9 on 2020-01-30 08:53

from django.db import migrations
from interactions.models import InteractionType, InteractionCategory

class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    def interactions_autocom_create(apps, schema_editor):
        category, _ = InteractionCategory.objects.get_or_create(category='emails')

        type = InteractionType.objects.create(
                                    name='email',
                                    category=category,
                                    slug='email',
                                    date_from_bool=True,
                                    subject_bool=True,
                                    summary_bool=True,
                                    note_bool=True,
                                    send_bool=True,
                                    settlement_bool=True,
                                    )

    def interactions_mailing_create(apps, schema_editor):
        category, _ = InteractionCategory.objects.get_or_create(category='emails')

        type = InteractionType.objects.create(
                                    name='email-mass',
                                    category=category,
                                    slug='email-mass',
                                    date_from_bool=True,
                                    subject_bool=True,
                                    summary_bool=True,
                                    attachment_bool=True,
                                    note_bool=True,
                                    send_bool=True,
                                    created_by_bool=True,
                                    handled_by_bool=True,
                                    settlement_bool=True,
                                    dispatched_bool=True,
                                    communication_type_bool=True,
                                    )

    operations = [
        migrations.RunPython(interactions_mailing_create, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(interactions_autocom_create, reverse_code=migrations.RunPython.noop),
    ]
