# Generated by Django 2.2.9 on 2020-02-05 09:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aklub', '0068_delete_result'),
        ('interactions', '0002_auto_20200130_0953'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interaction2',
            new_name='Interaction',
        ),
        migrations.RenameModel(
            old_name='Results',
            new_name='Result',
        ),
    ]
