# Generated by Django 2.2.9 on 2020-02-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0003_auto_20200205_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='petitionsignature',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Date of signature'),
        ),
    ]
