# Generated by Django 2.2.9 on 2020-02-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0004_petitionsignature_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='send',
        ),
        migrations.RemoveField(
            model_name='interactiontype',
            name='send_bool',
        ),
        migrations.AddField(
            model_name='interactiontype',
            name='send_email',
            field=models.BooleanField(blank=True, default=False, help_text='the email will be immediatelly sent to the user', null=True),
        ),
        migrations.AddField(
            model_name='interactiontype',
            name='send_sms',
            field=models.BooleanField(blank=True, default=False, help_text='the sms will be immediatelly send to the use', null=True),
        ),
    ]
