# Generated by Django 2.2.9 on 2020-02-13 13:21

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0005_auto_20200206_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interactiontype',
            name='date_from_bool',
        ),
        migrations.RemoveField(
            model_name='interactiontype',
            name='subject_bool',
        ),
        migrations.AlterField(
            model_name='interaction',
            name='date_from',
            field=models.DateTimeField(default=datetime.datetime.now(), verbose_name='Date of interaction'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interaction',
            name='date_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End of period date'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='subject',
            field=models.CharField(default='subject Text', help_text='The topic of this communication', max_length=130, verbose_name='Subject'),
            preserve_default=False,
        ),
    ]
