# Generated by Django 2.2.9 on 2020-02-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0007_auto_20200219_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='communication_type',
            field=models.CharField(blank=True, choices=[('mass', 'Mass'), ('auto', 'Automatic'), ('individual', 'Individual')], default='individual', max_length=30, verbose_name='Type of communication'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='next_step',
            field=models.TextField(blank=True, default='', help_text='What happens next', max_length=3000, verbose_name='Next steps'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='status',
            field=models.CharField(blank=True, default='', help_text='Status/progress of this communication', max_length=130, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='summary',
            field=models.TextField(blank=True, default='', help_text='Text or summary of this communication', max_length=50000, verbose_name='Text'),
        ),
    ]
