# Generated by Django 2.2.10 on 2020-04-02 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0007_auto_20200219_1404'),
    ]
    def handle_null_value(apps, schema_editor):
        Interaction = apps.get_model("interactions",'Interaction')
        new_step_null = Interaction.objects.filter(next_step__isnull=True)
        status_null = Interaction.objects.filter(status__isnull=True)
        summary_null = Interaction.objects.filter(summary__isnull=True)

        new_step_null.update(next_step="")
        status_null.update(next_step="")
        summary_null.update(next_step="")

    operations = [
        migrations.RunPython(handle_null_value, reverse_code=migrations.RunPython.noop), # pak na konec
    ]
