# Generated by Django 3.1 on 2021-11-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0013_auto_20210429_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactiontype',
            name='name',
            field=models.CharField(max_length=130, verbose_name='Interaction name'),
        ),
    ]
