# Generated by Django 3.1.14 on 2022-01-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_auto_20220114_2208'),
        ('interactions', '0014_auto_20211120_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='answer_to_additional_question_1',
            field=models.TextField(blank=True, default=False, null=True, verbose_name='Answer to additional question 1'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='answer_to_additional_question_2',
            field=models.TextField(blank=True, default=False, null=True, verbose_name='Answer to additional question 2'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='answer_to_additional_question_3',
            field=models.TextField(blank=True, default=False, null=True, verbose_name='Answer to additional question 3'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='answer_to_additional_question_4',
            field=models.TextField(blank=True, default=False, null=True, verbose_name='Answer to additional question 4'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='program_of_interest',
            field=models.ManyToManyField(related_name='programs_of_interest', to='events.Event', verbose_name='Program of interest'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='skills',
            field=models.TextField(blank=True, default=False, null=True, verbose_name='Skills'),
        ),
        migrations.AddField(
            model_name='interactiontype',
            name='answer_to_additional_question_1_bool',
            field=models.BooleanField(default=False, help_text='Choose if answer_to_additional_question_1 is visible in specific type of interaction.', verbose_name='Answer to additional question 1'),
        ),
        migrations.AddField(
            model_name='interactiontype',
            name='answer_to_additional_question_2_bool',
            field=models.BooleanField(default=False, help_text='Choose if answer_to_additional_question_2 is visible in specific type of interaction.', verbose_name='Answer to additional question 2'),
        ),
        migrations.AddField(
            model_name='interactiontype',
            name='answer_to_additional_question_3_bool',
            field=models.BooleanField(default=False, help_text='Choose if answer_to_additional_question_3 is visible in specific type of interaction.', verbose_name='Answer to additional question 3'),
        ),
        migrations.AddField(
            model_name='interactiontype',
            name='answer_to_additional_question_4_bool',
            field=models.BooleanField(default=False, help_text='Choose if answer_to_additional_question_4 is visible in specific type of interaction.', verbose_name='Answer to additional question 4'),
        ),
        migrations.AddField(
            model_name='interactiontype',
            name='skills_bool',
            field=models.BooleanField(default=False, help_text='Choose if skills is visible in specific type of interaction.', verbose_name='Skills'),
        ),
    ]
