# Generated by Django 3.1.14 on 2022-01-16 23:59

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0014_auto_20211120_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='program_of_interest',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('zmj', 'Zažít město jinak'), ('dpnk', 'Do práce na Kole'), ('lab', 'LAB')], max_length=600, verbose_name='Program of interest'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='skills',
            field=models.TextField(blank=True, verbose_name='Skills'),
        ),
        migrations.AddField(
            model_name='interactiontype',
            name='program_of_interest_bool',
            field=models.BooleanField(default=False, help_text='Choose if program_of_interest is visible in specific type of interaction.', verbose_name='Program of interest'),
        ),
        migrations.AddField(
            model_name='interactiontype',
            name='skills_bool',
            field=models.BooleanField(default=False, help_text='Choose if skills is visible in specific type of interaction.', verbose_name='Skills'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='summary',
            field=models.TextField(blank=True, default='', help_text='Text or summary of this communication', verbose_name='Text'),
        ),
    ]
