# Generated by Django 3.1.14 on 2022-01-24 17:50

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0015_auto_20220117_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactioncategory',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, help_text='Identifier of the Interaction Category', max_length=130, null=True, populate_from='category', verbose_name='Slug'),
        ),
    ]
