# Generated by Django 3.1.14 on 2024-04-05 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0016_interactioncategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='status',
        ),
        migrations.RemoveField(
            model_name='interactiontype',
            name='status_bool',
        ),
    ]
