# Generated by Django 3.1.14 on 2024-04-08 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0018_auto_20240405_0656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interactionstatus',
            options={'verbose_name': 'Interaction Status', 'verbose_name_plural': 'Interaction Statuses'},
        ),
    ]
