# Generated by Django 3.1.14 on 2024-04-08 14:38

from django.db import migrations, models
import django.db.models.deletion
import interactions.models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0019_auto_20240408_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='status',
            field=models.ForeignKey(default=interactions.models.InteractionStatus.get_default_pk, help_text='Status/progress of this communication', null=True, on_delete=django.db.models.deletion.SET_NULL, to='interactions.interactionstatus', verbose_name='Status'),
        ),
    ]
