# Generated by Django 2.1.5 on 2019-01-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0001_squashed_0007_auto_20171021_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='action_flag',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Addition'), (2, 'Change'), (3, 'Deletion')], verbose_name='action flag'),
        ),
    ]
