# Generated by Django 2.2.4 on 2019-08-12 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

# from apps.aklub.migrations.data_migration.old_user_profile_model_hack import Settings as settings


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_merge_20190120_1444'),
        ('aklub', '0002_auto_20171109_1518_squashed_0038_auto_20190807_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
