# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-21 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_auto_20171018_1023'),
        ('aklub', '0045_auto_20171020_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aklub.UserProfile', verbose_name='user', null=True, blank=True),
        ),
    ]
