version: 2
jobs:
  build:
    working_directory: /home/aplikace
    docker:
      - image: python:3.5

    steps:
      - checkout
      - run: echo "$(date +%Y).${CIRCLE_BUILD_NUM} $(git rev-parse --short HEAD)" > apps/aklub/static/version.txt
      - setup_remote_docker:
          reusable: true
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.03.1-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
         name: Build Docker image
         command: docker build -t built-image .
      - run:
         name: Deploy test Docker image
         command: |
            if [ "$DOCKER_USER" != "" ] ; then
              TAG="$(date +%Y).${CIRCLE_BUILD_NUM}"
              docker tag built-image:latest auto0mat/klub:$TAG
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker push auto0mat/klub:$TAG
            fi
      - run:
         name: Start PostGIS container
         command: |
            docker run -d --hostname postgres --name postgres -e POSTGRES_PASSWORD=password mdillon/postgis:9.6
      - run:
         name: Start RabbitMQ container
         command: |
            docker run -d --hostname redis --name redis redis
      - run:
         name: Test Docker container in Django
         command: |
            sleep 10
            docker run \
               --entrypoint="/home/aplikace/docker-test-entrypoint.sh" \
               --env DATABASE_HOST=postgres \
               --env DATABASE_NAME=postgres \
               --env DATABASE_USER=postgres \
               --env DATABASE_PASSWORD=password \
               --env SECRET_KEY=secret \
               --env REDIS_URL="redis://redis" \
               --link redis:redis \
               --link postgres:postgres \
               --name dpnk-test \
               built-image
