version: 2
jobs:
  build:
    working_directory: /home/aplikace
    docker:
      - image: python:3.9-bullseye

    steps:
      - checkout
      - run: echo "$(date +%Y).${CIRCLE_BUILD_NUM} $(git rev-parse --short HEAD)" > apps/aklub/static/version.txt
      - setup_remote_docker:
          reusable: true
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.03.1-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
         name: Build Docker image
         command: docker build -t built-image . --build-arg UID=1000
      - run:
         name: Deploy test Docker image
         command: |
            if [ "$DOCKER_USER" != "" ] ; then
              TAG="$(date +%Y).${CIRCLE_BUILD_NUM}"
              docker tag built-image:latest auto0mat/klub:$TAG
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker push auto0mat/klub:$TAG
            fi
