# Generated by Django 2.2.15 on 2020-08-28 10:11

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aklub', '0085_auto_20200709_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name of Pdf')),
                ('topic', models.CharField(max_length=200, verbose_name='Topic of Pdf')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date of creation')),
                ('related_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('pdf_file', models.FileField(upload_to='pdf_storage', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('administrative_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aklub.AdministrativeUnit', verbose_name='administrative unit')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Author of Pdf')),
            ],
        ),
    ]
