# Generated by Django 2.2.16 on 2020-10-26 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfstorage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Author of file'),
        ),
        migrations.AlterField(
            model_name='pdfstorage',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name of file'),
        ),
        migrations.AlterField(
            model_name='pdfstorage',
            name='pdf_file',
            field=models.FileField(upload_to='pdf_storage'),
        ),
        migrations.AlterField(
            model_name='pdfstorage',
            name='topic',
            field=models.CharField(max_length=200, verbose_name='Topic of file'),
        ),
    ]
