# Generated by Django 2.2.16 on 2020-12-09 10:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_storage', '0002_auto_20201026_1851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdfstorage',
            options={'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
        migrations.AlterField(
            model_name='pdfstorage',
            name='pdf_file',
            field=models.FileField(upload_to='pdf_storage', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='pdfstorage',
            name='related_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None, verbose_name='Related ids'),
        ),
    ]
