# Generated by Django 2.1.5 on 2019-01-20 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_auto_20181114_1448'),
        ('admin', '0002_auto_20190108_1629'),
    ]

    operations = [
    ]
