# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-21 09:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0006_auto_20171021_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='user',
        ),
        migrations.RenameField(
            model_name='logentry',
            old_name='user_profile',
            new_name='user',
        ),
    ]
