# Generated by Django 2.2.4 on 2019-08-26 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('import_export_celery', '0002_auto_20190826_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importjob',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importjob_create', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importjob_update', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
    ]
