# Generated by Django 2.2.8 on 2019-12-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_export_celery', '0005_auto_20191128_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importjob',
            name='model',
            field=models.CharField(choices=[('User profile', 'User profile'), ('Company profile', 'Company profile'), ('Donor Payment Channel', 'Donor Payment Channel'), ('Interactions', 'Interactions')], max_length=160, verbose_name='Name of model to import to'),
        ),
    ]
