# Generated by Django 3.1 on 2021-11-20 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advanced_filters', '0010_auto_20210130_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancedfilter',
            name='b64_fake_query',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='advancedfilter',
            name='b64_query',
            field=models.CharField(max_length=2048),
        ),
    ]
