# Generated by Django 3.1 on 2021-11-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_auto_20190826_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['content_type__app_label', 'content_type__model', 'codename'], 'verbose_name': 'permission', 'verbose_name_plural': 'permissions'},
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
