# Generated by Django 2.2.4 on 2019-09-12 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aklub', '0044_auto_20190909_1816'),
        ('smmapdfs', '0002_auto_20180611_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfSandwichTypeConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrative_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aklub.AdministrativeUnit')),
                ('pdfsandwichtype', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='smmapdfs.PdfSandwichType')),
            ],
        ),
        migrations.CreateModel(
            name='PdfSandwichFontConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrative_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aklub.AdministrativeUnit')),
                ('pdfsandwichfont', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='smmapdfs.PdfSandwichFont')),
            ],
        ),
        migrations.CreateModel(
            name='PdfSandwichEmailConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrative_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aklub.AdministrativeUnit')),
                ('pdfsandwichemail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='smmapdfs.PdfSandwichEmail')),
            ],
        ),
    ]
