# Generated by Django 2.2.7 on 2019-11-21 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smmapdfs_edit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfsandwichemailconnector',
            name='administrative_unit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aklub.AdministrativeUnit'),
        ),
        migrations.AlterField(
            model_name='pdfsandwichfontconnector',
            name='administrative_unit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aklub.AdministrativeUnit'),
        ),
        migrations.AlterField(
            model_name='pdfsandwichtypeconnector',
            name='administrative_unit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aklub.AdministrativeUnit'),
        ),
    ]
