# Generated by Django 2.2.8 on 2019-12-12 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smmapdfs_edit', '0002_auto_20191121_1640'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PdfSandwichFontConnector',
        ),
    ]
