# Generated by Django 2.0.1 on 2018-06-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_auto_20171018_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
