# Generated by Django 2.0.3 on 2018-05-25 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PdfSandwichABC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdfsandwichs', verbose_name='pdfsandwich PDF')),
                ('sent_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Sent time')),
            ],
        ),
        migrations.CreateModel(
            name='PdfSandwichEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('cs', 'Czech'), ('dsnkcs', 'Škola')], default=None, max_length=80, verbose_name='Language')),
                ('subject', models.CharField(max_length=512, verbose_name='Subject')),
                ('template', models.TextField(default="Dear {{name}},<br/>\n<a href='{{download_link|safe}}'>Here is your pdfsandwich.</a><br/>\n{{download_link|safe}}<br/>\nBye", verbose_name='Background template')),
            ],
        ),
        migrations.CreateModel(
            name='PdfSandwichFont',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Font name')),
                ('ttf', models.FileField(upload_to='pdfsandwich_fonts', verbose_name='Font')),
            ],
        ),
        migrations.CreateModel(
            name='PdfSandwichType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Template name')),
                ('template_pdf', models.FileField(blank=True, null=True, upload_to='pdfsandwich_types', verbose_name='PDF template')),
                ('height', models.IntegerField(default=210, verbose_name='Height (mm)')),
                ('width', models.IntegerField(default=297, verbose_name='Width (mm)')),
            ],
        ),
        migrations.AddField(
            model_name='pdfsandwichemail',
            name='pdfsandwich_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdfsandwich_emails', to='smmapdfs.PdfSandwichType'),
        ),
        migrations.AddField(
            model_name='pdfsandwichabc',
            name='pdfsandwich_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='smmapdfs.PdfSandwichType', verbose_name='PDF sandwich template/type'),
        ),
    ]
