# Generated by Django 2.0.3 on 2018-06-11 18:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smmapdfs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfsandwichtype',
            name='template_pdf',
            field=models.FileField(default=None, upload_to='pdfsandwich_types', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='PDF template'),
            preserve_default=False,
        ),
    ]
