# Generated by Django 2.2.4 on 2019-08-27 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0035_preference_tables_create'),
        ('smmapdfs', '0002_auto_20180611_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfsandwichemail',
            name='administrative_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aklub.AdministrativeUnit'),
        ),
        migrations.AddField(
            model_name='pdfsandwichfont',
            name='administrative_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aklub.AdministrativeUnit'),
        ),
        migrations.AddField(
            model_name='pdfsandwichtype',
            name='administrative_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aklub.AdministrativeUnit'),
        ),
    ]
