# Generated by Django 2.2.6 on 2019-10-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('html_template_editor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='edited_crop',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
