# Generated by Django 2.2.9 on 2020-01-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('html_template_editor', '0002_auto_20191014_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='background_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='images',
            name='template_url',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
