# Generated by Django 2.2.10 on 2020-02-17 08:50

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('html_template_editor', '0003_auto_20200130_0656'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Company email')),
            ],
            options={
                'verbose_name': 'Company email',
                'verbose_name_plural': 'Company email',
            },
        ),
        migrations.CreateModel(
            name='CompanyPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone number')),
            ],
            options={
                'verbose_name': 'Company phone number',
                'verbose_name_plural': 'Company phone numbers',
            },
        ),
        migrations.CreateModel(
            name='CompanySocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_name', models.CharField(blank=True, choices=[('facebook', 'facebook'), ('google', 'google'), ('instagram', 'instagram'), ('twitter', 'twitter'), ('vimeo', 'vimeo'), ('youtube', 'youtube')], max_length=20, null=True, verbose_name='Icon name')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Social media',
                'verbose_name_plural': 'Social media',
            },
        ),
        migrations.CreateModel(
            name='CompanyUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Company url',
                'verbose_name_plural': 'Company urls',
            },
        ),
        migrations.CreateModel(
            name='TemplateFooter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=80, null=True, verbose_name='Company name')),
                ('address', models.CharField(blank=True, max_length=80, null=True, verbose_name='Address')),
                ('show', models.BooleanField(default=False, help_text='Show footer', verbose_name='Show')),
                ('email', models.ManyToManyField(blank=True, to='html_template_editor.CompanyEmail', verbose_name='Email')),
                ('phone', models.ManyToManyField(blank=True, to='html_template_editor.CompanyPhone', verbose_name='Phone')),
                ('social_media', models.ManyToManyField(blank=True, to='html_template_editor.CompanySocialMedia', verbose_name='Social media')),
                ('url', models.ManyToManyField(blank=True, to='html_template_editor.CompanyUrl', verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Template footer',
                'verbose_name_plural': 'Template footers',
            },
        ),
    ]
