# Generated by Django 2.2.10 on 2020-03-02 12:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('html_template_editor', '0004_companyemail_companyphone_companysocialmedia_companyurl_templatefooter'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatecontent',
            name='styles',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
