# Generated by Django 2.2.10 on 2020-04-14 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import html_template_editor.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('html_template_editor', '0006_auto_20200414_0736'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Header name')),
                ('text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Header text')),
                ('text_horizontal_position', models.CharField(blank=True, choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=20, null=True, verbose_name='Header horizontal text position')),
                ('text_vertical_position', models.CharField(blank=True, choices=[('top', 'Top'), ('middle', 'Middle'), ('bottom', 'Bottom')], default='middle', max_length=20, null=True, verbose_name='Header vertical text position')),
                ('logo', models.ImageField(help_text='Max. image width 300 px, and max. image file size 5 MB', upload_to='images', validators=[html_template_editor.validators.validate_logo_image], verbose_name='Logo image')),
                ('logo_horizontal_position', models.CharField(blank=True, choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=20, null=True, verbose_name='Logo horizontal position')),
                ('logo_position', models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right')], default='left', help_text='Left or right column logo position', max_length=20, null=True, verbose_name='Logo position')),
                ('show', models.BooleanField(default=False, help_text='Show header', verbose_name='Show')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Template header',
                'verbose_name_plural': 'Template headers',
            },
        ),
    ]
