# Generated by Django 2.2.12 on 2020-04-25 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('html_template_editor', '0007_templateheader'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatefooter',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Footer name'),
        ),
        migrations.AddField(
            model_name='templatefooter',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
