# Generated by Django 2.2.12 on 2020-05-11 06:23

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('html_template_editor', '0008_auto_20200425_0532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyemail',
            options={'verbose_name': 'Company email', 'verbose_name_plural': 'Company emails'},
        ),
        migrations.AlterModelOptions(
            name='companysocialmedia',
            options={'verbose_name': 'Company social media', 'verbose_name_plural': 'Company social media'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Images', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='templatecontent',
            options={'verbose_name': 'Template content', 'verbose_name_plural': 'Template contents'},
        ),
        migrations.AlterField(
            model_name='images',
            name='background_image',
            field=models.BooleanField(default=False, verbose_name='Background image'),
        ),
        migrations.AlterField(
            model_name='images',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='images',
            name='edited_crop',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Edited crop'),
        ),
        migrations.AlterField(
            model_name='images',
            name='edited_direction',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Edited direction'),
        ),
        migrations.AlterField(
            model_name='images',
            name='edited_width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Edited width'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(null=True, upload_to='images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='images',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='images',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='images',
            name='template_url',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Template url'),
        ),
        migrations.AlterField(
            model_name='templatecontent',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='templatecontent',
            name='images',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Images'),
        ),
        migrations.AlterField(
            model_name='templatecontent',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='templatecontent',
            name='page',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pages'),
        ),
        migrations.AlterField(
            model_name='templatecontent',
            name='regions',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Regions'),
        ),
        migrations.AlterField(
            model_name='templatecontent',
            name='styles',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Styles'),
        ),
        migrations.AlterField(
            model_name='templatecontent',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Universally unique identifier'),
        ),
        migrations.AlterField(
            model_name='templatefooter',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='templateheader',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
