# Generated by Django 2.2.14 on 2020-07-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('html_template_editor', '0009_auto_20200511_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysocialmedia',
            name='icon_name',
            field=models.CharField(blank=True, choices=[('facebook', 'facebook'), ('google', 'google'), ('instagram', 'instagram'), ('twitter', 'twitter'), ('vimeo', 'vimeo'), ('youtube', 'youtube')], max_length=20, null=True, verbose_name='Icon name'),
        ),
    ]
