# Generated by Django 2.1.5 on 2019-01-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0012_auto_20190114_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telephone',
            name='is_primary',
            field=models.BooleanField(blank=True, default=False, verbose_name='Primary phone'),
        ),
    ]
