# Generated by Django 2.1.5 on 2019-02-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0012_auto_20190128_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telephone',
            name='is_primary',
            field=models.NullBooleanField(default=False, verbose_name='Primary phone'),
        ),
        migrations.AlterUniqueTogether(
            name='telephone',
            unique_together={('user', 'is_primary')},
        ),
    ]
