# Generated by Django 2.1.5 on 2019-01-28 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0012_auto_20190128_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='campaigns',
        ),
    ]
