# Generated by Django 2.1.5 on 2019-01-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0013_remove_userprofile_campaigns'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Bank account number'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(help_text='Choose some unique name for this campaign', max_length=100, verbose_name='Name'),
        ),
    ]
