# Generated by Django 2.1.2 on 2018-12-11 17:05

from django.db import migrations
import django_grapesjs.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0014_auto_20181211_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masscommunication',
            name='template',
            field=django_grapesjs.models.fields.GrapesJsHtmlField(),
        ),
    ]
