# Generated by Django 2.1.5 on 2019-01-20 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0012_auto_20190108_1629'),
        ('aklub', '0015_auto_20181211_1705'),
    ]

    operations = [
    ]
