# Generated by Django 2.1.7 on 2019-02-26 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0016_auto_20190212_1543'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='telephone',
            unique_together={('user', 'is_primary')},
        ),
    ]
