# Generated by Django 2.1.5 on 2019-01-22 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0016_auto_20190122_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorpaymentchannel',
            name='event',
            field=models.ManyToManyField(blank=True, null=True, related_name='donorevents', to='aklub.Event'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user_donor_payment_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paymentchannels', to='aklub.DonorPaymentChannel'),
        ),
    ]
