# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 13:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0016_auto_20151211_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automaticcommunication',
            name='condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aklub.Condition'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_communication', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_by_communication', to=settings.AUTH_USER_MODEL, verbose_name='Last handled by'),
        ),
        migrations.AlterField(
            model_name='terminalcondition',
            name='operation',
            field=models.CharField(choices=[('=', '='), ('!=', '≠'), ('>', '>'), ('<', '<'), ('>=', '≤'), ('<=', '≤'), ('containts', 'contains'), ('icontaints', 'contains (case insensitive)')], max_length=30, verbose_name='Operation'),
        ),
        migrations.AlterField(
            model_name='terminalcondition',
            name='variable',
            field=models.CharField(blank=True, choices=[('User.active', 'User Aktivní: BooleanField '), ('User.activity_points', 'User Body za aktivitu: IntegerField '), ('User.additional_information', 'User Rozšiřující informace: TextField '), ('User.addressment', 'User Oslovení v dopise: CharField '), ('User.addressment_on_envelope', 'User Oslovení na obálku: CharField '), ('User.city', 'User Město/Městská část: CharField '), ('User.club_card_available', 'User Nárok na klubovou kartu: BooleanField '), ('User.club_card_dispatched', 'User Klubová karta odeslána?: BooleanField '), ('User.country', 'User Země: CharField '), ('User.different_correspondence_address', 'User Jiná korespondenční adresa: BooleanField '), ('User.email', 'User Email: CharField '), ('User.exceptional_membership', 'User Výjimečné členství: BooleanField '), ('User.expected_date_of_first_payment', 'User Očekávané datum první platby: DateField '), ('User.expected_regular_payment_date', 'User expected regular payment date: DateField '), ('User.extra_money', 'User extra money: IntegerField '), ('User.field_of_work', 'User Pracovní oblast: CharField '), ('User.firstname', 'User Jméno: CharField '), ('User.id', 'User ID: AutoField '), ('User.knows_us_from', 'User Odkud nás zná?: CharField '), ('User.language', "User Jazyk: CharField ('cs', 'en')"), ('User.last_payment', 'User last payment: DenormDBField '), ('User.no_upgrade', 'User no upgrade: NullBooleanField '), ('User.note', 'User Poznámka pro oživení nudného formuláře: TextField '), ('User.number_of_payments', 'User number of payments: IntegerField '), ('User.old_account', 'User Starý účet: BooleanField '), ('User.other_benefits', 'User Další benefity: TextField '), ('User.other_support', 'User Jiná podpora: TextField '), ('User.payment_total', 'User payment total: FloatField '), ('User.profile_picture', 'User Profilová fotografie: FileField '), ('User.profile_text', 'User A jaký je Tvůj důvod?: TextField '), ('User.public', 'User Zveřejnit mé jméno v seznamu podporovatelů: BooleanField '), ('User.recruiter', 'User recruiter: ForeignKey '), ('User.registered_support', 'User Registrace podpory: DateTimeField '), ('User.regular_amount', 'User Částka pravidelné platby: PositiveIntegerField '), ('User.regular_frequency', "User Frekvence pravidelných plateb: CharField ('monthly', 'quaterly', 'biannually', 'annually')"), ('User.regular_payments', 'User Pravidelné platby: BooleanField '), ('User.sex', "User Pohlaví: CharField ('male', 'female', 'unknown')"), ('User.source', 'User Zdroj: ForeignKey '), ('User.street', 'User Ulice a číslo domu (č.p./č.o.): CharField '), ('User.surname', 'User Příjmení: CharField '), ('User.telephone', 'User Telefon: CharField '), ('User.title_after', 'User Titul za jménem: CharField '), ('User.title_before', 'User Titul před jménem: CharField '), ('User.variable_symbol', 'User Variabilní symbol: CharField '), ('User.verified', 'User Ověřen: BooleanField '), ('User.verified_by', 'User Ověřil: ForeignKey '), ('User.why_supports', 'User Proč nás podporuje?: TextField '), ('User.wished_information', 'User Zasílat pravidelné informace emailem: BooleanField '), ('User.wished_tax_confirmation', 'User Zaslat daňové potvrzení (na konci roku): BooleanField '), ('User.wished_welcome_letter', 'User Odeslat uvítací dopis s členskou kartou: BooleanField '), ('User.zip_code', 'User PSČ: CharField '), ('User.last_payment.BIC', 'User.last_payment BIC: CharField '), ('User.last_payment.KS', 'User.last_payment KS: CharField '), ('User.last_payment.SS', 'User.last_payment SS: CharField '), ('User.last_payment.VS', 'User.last_payment VS: CharField '), ('User.last_payment.account', 'User.last_payment Account: CharField '), ('User.last_payment.account_name', 'User.last_payment Jméno účtu: CharField '), ('User.last_payment.account_statement', 'User.last_payment account statement: ForeignKey '), ('User.last_payment.amount', 'User.last_payment Částka: PositiveIntegerField '), ('User.last_payment.bank_code', 'User.last_payment Kód banky: CharField '), ('User.last_payment.bank_name', 'User.last_payment Jméno banky: CharField '), ('User.last_payment.date', 'User.last_payment Datum platby: DateField '), ('User.last_payment.done_by', 'User.last_payment Provedl: CharField '), ('User.last_payment.id', 'User.last_payment ID: AutoField '), ('User.last_payment.type', "User.last_payment Typ: CharField ('bank-transfer', 'cash', 'expected', 'darujme')"), ('User.last_payment.user', 'User.last_payment user: ForeignKey '), ('User.last_payment.user_identification', 'User.last_payment Identifikace odesílatele: CharField '), ('User.source.direct_dialogue', 'User.source Pochází z Direct dialogu: BooleanField '), ('User.source.id', 'User.source ID: AutoField '), ('User.source.name', 'User.source Jméno: CharField '), ('User.source.slug', 'User.source Identifikátor: SlugField '), ('action', "Akce: CharField ('daily', 'new-user', 'new-payment')")], help_text='Value or variable on left-hand side', max_length=50, null=True, verbose_name='Variable'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_payment',
            field=models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_last_payment', to='aklub.Payment'),
        ),
        migrations.AlterField(
            model_name='user',
            name='recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aklub.Recruiter'),
        ),
        migrations.AlterField(
            model_name='user',
            name='source',
            field=models.ForeignKey(blank=True, default=None, help_text='How did he contact us / became a member? In direct dialog, please distinguish between partial form (he still needs to send a permanent order into his bank) and full form (we are going to submit his form directly into bank, no further action is needed from him).', max_length=80, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aklub.Source', verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='user',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_users', to=settings.AUTH_USER_MODEL, verbose_name='Verified by'),
        ),
    ]
