# Generated by Django 2.1.7 on 2019-02-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0017_auto_20190226_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telephone',
            name='is_primary',
            field=models.NullBooleanField(choices=[(None, 'No'), (True, 'Yes')], default=None, verbose_name='Primary phone'),
        ),
    ]
