# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0017_auto_20160127_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='VS',
            field=models.CharField(blank=True, help_text='Variable symbol', max_length=30, null=True, verbose_name='VS'),
        ),
    ]
