# Generated by Django 2.1.5 on 2019-01-20 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0017_auto_20190120_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to=settings.AUTH_USER_MODEL),
        ),
    ]
