# Generated by Django 2.1.7 on 2019-03-19 10:32

import aklub.autocom
from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0018_auto_20190227_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automaticcommunication',
            name='sent_to_users',
            field=models.ManyToManyField(blank=True, help_text='List of users to whom this communication was already sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='masscommunication',
            name='subject',
            field=models.CharField(help_text='Same variables as in template can be used', max_length=130, validators=[aklub.autocom.gendrify_text, django.core.validators.RegexValidator('^([^$]*(\\$(addressment|name|firstname|surname|street|city|zipcode|email|regular_amount|regular_frequency|var_symbol|last_payment_amount|auth_token)\\b)?)*$', 'Unknown variable')], verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='masscommunication',
            name='subject_en',
            field=models.CharField(blank=True, help_text='English version of the subject. If empty, English speaking users will not receive this communication.<br/>Same variables as in template can be used', max_length=130, null=True, validators=[aklub.autocom.gendrify_text, django.core.validators.RegexValidator('^([^$]*(\\$(addressment|name|firstname|surname|street|city|zipcode|email|regular_amount|regular_frequency|var_symbol|last_payment_amount|auth_token)\\b)?)*$', 'Unknown variable')], verbose_name='English subject'),
        ),
        migrations.AlterField(
            model_name='masscommunication',
            name='template',
            field=models.TextField(help_text='Template can contain following variable substitutions: <br/>{mr|mrs} or {mr/mrs}, $addressment, $name, $firstname, $surname, $street, $city, $zipcode, $email, $regular_amount, $regular_frequency, $var_symbol, $last_payment_amount, $auth_token', max_length=50000, null=True, validators=[aklub.autocom.gendrify_text, django.core.validators.RegexValidator('^([^$]*(\\$(addressment|name|firstname|surname|street|city|zipcode|email|regular_amount|regular_frequency|var_symbol|last_payment_amount|auth_token)\\b)?)*$', 'Unknown variable')], verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='masscommunication',
            name='template_en',
            field=models.TextField(blank=True, help_text='Same variables as in template can be used', max_length=50000, null=True, validators=[aklub.autocom.gendrify_text, django.core.validators.RegexValidator('^([^$]*(\\$(addressment|name|firstname|surname|street|city|zipcode|email|regular_amount|regular_frequency|var_symbol|last_payment_amount|auth_token)\\b)?)*$', 'Unknown variable')], verbose_name='English template'),
        ),
    ]
