# Generated by Django 2.1.5 on 2019-01-20 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0020_interaction_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorPaymentChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VS', models.CharField(blank=True, help_text='Variable symbol', max_length=30, null=True, verbose_name='VS')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='aklub.Payment')),
            ],
            options={
                'verbose_name': 'Donor payment channel',
                'verbose_name_plural': 'Donor payment channels',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='donor_payment_channel',
            field=models.ManyToManyField(blank=True, null=True, related_name='donorpaymentchannels', to='aklub.DonorPaymentChannel'),
        ),
    ]
