# Generated by Django 2.1.7 on 2019-03-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0020_auto_20190326_1153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbankaccount',
            options={'verbose_name': 'User bank account', 'verbose_name_plural': 'User bank accounts'},
        ),
        migrations.AlterField(
            model_name='event',
            name='created',
            field=models.DateField(blank=True, null=True, verbose_name='Created'),
        ),
    ]
