# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-23 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0020_auto_20160529_1514'),
    ]

    operations = [
        migrations.RenameModel(
            "User",
            "UserInCampaign"
        ),
    ]
