# Generated by Django 2.1.7 on 2019-03-29 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0021_auto_20190329_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorpaymentchannel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userchannels', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
