# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-25 12:42
from __future__ import unicode_literals

from django.db import migrations
import datetime

def create_userprofiles(apps, schema_editor):
    User = apps.get_model("auth", "User")
    UserProfile = apps.get_model("aklub", "UserProfile")
    UserInCampaign = apps.get_model("aklub", "UserInCampaign")
    Campaign = apps.get_model("aklub", "Campaign")
    campaign = Campaign.objects.create(
        created=datetime.date.today(),
        name="Defaultní kampaň",
        description="Kampaň, kam spadli všichni uživetelé po vytvoření Uživatele v kampani",
    )
    for uic in UserInCampaign.objects.all():
        user = User.objects.create(
            username='%s%s' % (uic.email.split('@', 1)[0], User.objects.count()),
            first_name=uic.firstname,
            last_name=uic.surname,
            email=uic.email,
        )
        print(uic.email)
        wished_information = False if uic.wished_information == None else uic.wished_information
        userprofile = UserProfile.objects.create(
            user=user,
            title_before=uic.title_before,
            title_after=uic.title_after,
            sex=uic.sex,
            addressment=uic.addressment,
            addressment_on_envelope=uic.addressment_on_envelope,
            language=uic.language,
            telephone=uic.telephone,
            street=uic.street,
            city=uic.city,
            country=uic.country,
            zip_code=uic.zip_code,
            different_correspondence_address=uic.different_correspondence_address,
            other_support=uic.other_support,
            public=uic.public,
            wished_tax_confirmation=uic.wished_tax_confirmation,
            wished_welcome_letter=uic.wished_welcome_letter,
            wished_information=wished_information,
            active=uic.active,
            profile_text=uic.profile_text,
            profile_picture=uic.profile_picture,
            club_card_available=uic.club_card_available,
            club_card_dispatched=uic.club_card_dispatched,
            other_benefits=uic.other_benefits,
            note=uic.note,
            recruiter=uic.recruiter,
        )
        userprofile.campaigns=uic.campaigns.all()
        uic.campaign = campaign
        uic.userprofile = userprofile
        uic.save()



class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0023_auto_20160625_1242'),
    ]

    operations = [
        migrations.RunPython(create_userprofiles)
    ]
