# Generated by Django 2.1.7 on 2019-03-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0024_auto_20190325_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='note',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Note for making a boring form more lively'),
        ),
    ]
