# Generated by Django 2.1.7 on 2019-06-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0024_auto_20190606_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automaticcommunication',
            name='sent_to_users',
            field=models.ManyToManyField(blank=True, help_text='List of users to whom this communication was already sent', to='aklub.DonorPaymentChannel'),
        ),
    ]
