# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0024_auto_20160625_1242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userincampaign',
            options={'ordering': ('userprofile__user__last_name', 'userprofile__user__last_name'), 'verbose_name': 'User in campaign', 'verbose_name_plural': 'Users in campaign'},
        ),
        migrations.RemoveField(
            model_name='userincampaign',
            name='active',
        ),
        migrations.RemoveField(
            model_name='userincampaign',
            name='addressment',
        ),
        migrations.RemoveField(
            model_name='userincampaign',
            name='addressment_on_envelope',
        ),
        migrations.RemoveField(
            model_name='userincampaign',
            name='campaigns',
        ),
        migrations.RemoveField(
            model_name='userincampaign',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userincampaign',
            name='club_card_available',
        ),
        migrations.RemoveField(
            model_name='userincampaign',
            name='club_card_dispatched',
        ),
        migrations.RemoveField(
            model_name='userincampaign',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userincampaign',
            name='different_correspondence_address',
        ),
        migrations.RemoveField(
            model_name='userincampaign',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userincampaign',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='userincampaign',
            name='language',
        ),
        migrations.RemoveField(
            model_name='userincampaign',
            name='other_benefits',
        ),
        migrations.RemoveField(
            model_name='userincampaign',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='userincampaign',
            name='profile_text',
        ),
        migrations.RemoveField(
            model_name='userincampaign',
            name='public',
        ),
        migrations.RemoveField(
            model_name='userincampaign',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='userincampaign',
            name='street',
        ),
        migrations.RemoveField(
            model_name='userincampaign',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='userincampaign',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='userincampaign',
            name='title_after',
        ),
        migrations.RemoveField(
            model_name='userincampaign',
            name='title_before',
        ),
        migrations.RemoveField(
            model_name='userincampaign',
            name='zip_code',
        ),
        migrations.AlterField(
            model_name='terminalcondition',
            name='variable',
            field=models.CharField(blank=True, choices=[('UserInCampaign.activity_points', 'UserInCampaign Body za aktivitu: IntegerField '), ('UserInCampaign.additional_information', 'UserInCampaign Rozšiřující informace: TextField '), ('UserInCampaign.campaign', 'UserInCampaign campaign: ForeignKey '), ('UserInCampaign.exceptional_membership', 'UserInCampaign Výjimečné členství: BooleanField '), ('UserInCampaign.expected_date_of_first_payment', 'UserInCampaign Očekávané datum první platby: DateField '), ('UserInCampaign.expected_regular_payment_date', 'UserInCampaign expected regular payment date: DateField '), ('UserInCampaign.extra_money', 'UserInCampaign extra money: IntegerField '), ('UserInCampaign.field_of_work', 'UserInCampaign Pracovní oblast: CharField '), ('UserInCampaign.id', 'UserInCampaign ID: AutoField '), ('UserInCampaign.knows_us_from', 'UserInCampaign Odkud nás zná?: CharField '), ('UserInCampaign.last_payment', 'UserInCampaign last payment: DenormDBField '), ('UserInCampaign.no_upgrade', 'UserInCampaign no upgrade: NullBooleanField '), ('UserInCampaign.note', 'UserInCampaign Poznámka pro oživení nudného formuláře: TextField '), ('UserInCampaign.number_of_payments', 'UserInCampaign number of payments: IntegerField '), ('UserInCampaign.old_account', 'UserInCampaign Starý účet: BooleanField '), ('UserInCampaign.other_support', 'UserInCampaign Jiná podpora: TextField '), ('UserInCampaign.payment_total', 'UserInCampaign payment total: FloatField '), ('UserInCampaign.registered_support', 'UserInCampaign Registrace podpory: DateTimeField '), ('UserInCampaign.regular_amount', 'UserInCampaign Částka pravidelné platby: PositiveIntegerField '), ('UserInCampaign.regular_frequency', "UserInCampaign Frekvence pravidelných plateb: CharField ('monthly', 'quaterly', 'biannually', 'annually')"), ('UserInCampaign.regular_payments', 'UserInCampaign Pravidelné platby: BooleanField '), ('UserInCampaign.source', 'UserInCampaign Zdroj: ForeignKey '), ('UserInCampaign.userprofile', 'UserInCampaign userprofile: ForeignKey '), ('UserInCampaign.variable_symbol', 'UserInCampaign Variabilní symbol: CharField '), ('UserInCampaign.verified', 'UserInCampaign Ověřen: BooleanField '), ('UserInCampaign.verified_by', 'UserInCampaign Ověřil: ForeignKey '), ('UserInCampaign.why_supports', 'UserInCampaign Proč nás podporuje?: TextField '), ('UserInCampaign.last_payment.BIC', 'UserInCampaign.last_payment BIC: CharField '), ('UserInCampaign.last_payment.KS', 'UserInCampaign.last_payment KS: CharField '), ('UserInCampaign.last_payment.SS', 'UserInCampaign.last_payment SS: CharField '), ('UserInCampaign.last_payment.VS', 'UserInCampaign.last_payment VS: CharField '), ('UserInCampaign.last_payment.account', 'UserInCampaign.last_payment Account: CharField '), ('UserInCampaign.last_payment.account_name', 'UserInCampaign.last_payment Jméno účtu: CharField '), ('UserInCampaign.last_payment.account_statement', 'UserInCampaign.last_payment account statement: ForeignKey '), ('UserInCampaign.last_payment.amount', 'UserInCampaign.last_payment Částka: PositiveIntegerField '), ('UserInCampaign.last_payment.bank_code', 'UserInCampaign.last_payment Kód banky: CharField '), ('UserInCampaign.last_payment.bank_name', 'UserInCampaign.last_payment Jméno banky: CharField '), ('UserInCampaign.last_payment.currency', 'UserInCampaign.last_payment Currency: CharField '), ('UserInCampaign.last_payment.date', 'UserInCampaign.last_payment Datum platby: DateField '), ('UserInCampaign.last_payment.done_by', 'UserInCampaign.last_payment Provedl: CharField '), ('UserInCampaign.last_payment.id', 'UserInCampaign.last_payment ID: AutoField '), ('UserInCampaign.last_payment.operation_id', 'UserInCampaign.last_payment Operation ID: CharField '), ('UserInCampaign.last_payment.order_id', 'UserInCampaign.last_payment Order ID: CharField '), ('UserInCampaign.last_payment.recipient_message', 'UserInCampaign.last_payment Recipient message: CharField '), ('UserInCampaign.last_payment.specification', 'UserInCampaign.last_payment Specification: CharField '), ('UserInCampaign.last_payment.transfer_note', 'UserInCampaign.last_payment Transfer note: CharField '), ('UserInCampaign.last_payment.transfer_type', 'UserInCampaign.last_payment Transfer type: CharField '), ('UserInCampaign.last_payment.type', "UserInCampaign.last_payment Typ: CharField ('bank-transfer', 'cash', 'expected', 'darujme')"), ('UserInCampaign.last_payment.user', 'UserInCampaign.last_payment user: ForeignKey '), ('UserInCampaign.last_payment.user_identification', 'UserInCampaign.last_payment Identifikace odesílatele: CharField '), ('UserInCampaign.source.direct_dialogue', 'UserInCampaign.source Pochází z Direct dialogu: BooleanField '), ('UserInCampaign.source.id', 'UserInCampaign.source ID: AutoField '), ('UserInCampaign.source.name', 'UserInCampaign.source Jméno: CharField '), ('UserInCampaign.source.slug', 'UserInCampaign.source Identifikátor: SlugField '), ('action', "Akce: CharField ('daily', 'new-user', 'new-payment')")], help_text='Value or variable on left-hand side', max_length=50, null=True, verbose_name='Variable'),
        ),
    ]
