# Generated by Django 2.1.5 on 2019-01-20 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0024_auto_20190120_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorpaymentchannel',
            name='bank_account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bankaccounts', to='aklub.BankAccount'),
        ),
    ]
