# Generated by Django 2.1.5 on 2019-01-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0025_auto_20190120_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='donor_payment_channel',
            field=models.ManyToManyField(blank=True, related_name='donorpaymentchannels', to='aklub.DonorPaymentChannel'),
        ),
    ]
