# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-25 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0026_auto_20160722_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='darujme_name',
            field=models.CharField(blank=True, help_text='Choose some unique name for this campaign', max_length=100, verbose_name='Name'),
        ),
    ]
