# Generated by Django 2.1.7 on 2019-06-21 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from .data_migration.old_user_profile_model_hack import Settings as settings


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0027_auto_20190618_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetitionSignature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True, verbose_name='Date and time of the communication')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date of creation')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date of last change')),
                ('email_confirmed', models.BooleanField(default=False, verbose_name='Is confirmed via e-mail')),
                ('gdpr_consent', models.BooleanField(default=False, verbose_name='GDPR consent')),
                ('public', models.BooleanField(default=False, verbose_name='Publish my name in the list of supporters/petitents of this campaign')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aklub.Event', verbose_name='Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='interaction',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date of creation'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date of last change'),
        ),
        migrations.AlterField(
            model_name='donorpaymentchannel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userchannels', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Date and time of the communication'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aklub.Event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
