# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-31 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0028_auto_20160728_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='darujme_api_id',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Name in Darujme.cz'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='darujme_api_secret',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Name in Darujme.cz'),
        ),
    ]
