# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-08-09 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0030_auto_20160809_1112'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userincampaign',
            unique_together=set([('userprofile', 'campaign')]),
        ),
    ]
