# Generated by Django 2.2.3 on 2019-07-29 19:37

from django.db import migrations, models
import django.db.models.deletion
import aklub.models


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0032_split_profile_remove_pk_for_profile_ptr_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aklub.Profile'), # remove primary_key=True, add null=True
            preserve_default=True,
        ),
    ]
