# Generated by Django 2.2.3 on 2019-08-05 11:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0032_auto_20190801_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativeunit',
            name='ico',
            field=models.CharField(blank=True, default=None, max_length=8, null=True, validators=[django.core.validators.RegexValidator('^.{8}$', 'IČO není zadáno ve správném formátu. Zkontrolujte že číslo má osm číslic a případně ho doplňte nulami zleva.'), django.core.validators.RegexValidator('^[0-9]*$', 'IČO musí být číslo')], verbose_name='IČO'),
        ),
    ]
