# Generated by Django 2.2.3 on 2019-08-12 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0032_auto_20190801_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='administrative_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aklub.AdministrativeUnit', verbose_name='administrative units'),
        ),
    ]
