# Generated by Django 2.2.4 on 2019-08-19 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0033_interaction_administrative_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsletter_on', models.NullBooleanField(default=False, verbose_name='newsletter_on')),
                ('call_on', models.NullBooleanField(default=False, verbose_name='call_on')),
                ('challenge_on', models.NullBooleanField(default=False, verbose_name='challenge_on')),
                ('letter_on', models.NullBooleanField(default=False, verbose_name='letter_on')),
                ('send_mailing_lists', models.BooleanField(default=True, verbose_name='Sending of mailing lists allowed')),
                ('public', models.BooleanField(default=True, verbose_name='Publish my name in the list of supporters')),
                ('administrative_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aklub.AdministrativeUnit', verbose_name='administrative unit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
