# Generated by Django 2.2.4 on 2019-08-19 14:16

from django.db import migrations

from .data_migration import preference_model_create


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0034_auto_20190819_1530'),
    ]

    operations = [
        migrations.RunPython(preference_model_create.preference_model_create),
    ]
