# Generated by Django 2.2.4 on 2019-08-21 16:16

import django.core.validators
from django.db import migrations
import stdnumfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0035_preference_model_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='crn',
            field=stdnumfield.models.StdNumField(alphabets=[None], blank=True, default=11111111, error_messages={'stdnum_format': 'CRN format is incorrect. Check that the number has eight digits, and if necessary, add zeros from the left.'}, formats=['cz.dic'], null=True, validators=[django.core.validators.RegexValidator('^[0-9]{8}$', 'CRN must be integer number')], verbose_name='Company Registration Number'),
        ),
    ]
