# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0035_auto_20160907_1356'),
        ('aklub', '0035_auto_20160916_1514'),
    ]

    operations = [
    ]
