# Generated by Django 2.2.4 on 2019-08-02 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0035_split_profile_add_pk_for_profile_ptr_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorpaymentchannel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userchannels', to='aklub.Profile', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_communication', to='aklub.Profile', verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_by_communication', to='aklub.Profile', verbose_name='Last handled by'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aklub.Profile', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='masscommunication',
            name='send_to_users',
            field=models.ManyToManyField(blank=True, help_text='All users who should receive the communication', limit_choices_to={'is_active': 'True', 'send_mailing_lists': 'True'}, to='aklub.Profile', verbose_name='send to users'),
        ),
        migrations.AlterField(
            model_name='petitionsignature',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aklub.Profile', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='taxconfirmation',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aklub.Profile'),
        ),
        migrations.AlterField(
            model_name='telephone',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aklub.Profile'),
        ),
        migrations.AlterField(
            model_name='terminalcondition',
            name='variable',
            field=models.CharField(blank=True, choices=[('Profile.addressment', 'Profile Addressment in letter: CharField '), ('Profile.addressment_on_envelope', 'Profile Addressment on envelope: CharField '), ('Profile.age_group', 'Profile Birth year: PositiveIntegerField (2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000, 1999, 1998, 1997, 1996, 1995, 1994, 1993, 1992, 1991, 1990, 1989, 1988, 1987, 1986, 1985, 1984, 1983, 1982, 1981, 1980, 1979, 1978, 1977, 1976, 1975, 1974, 1973, 1972, 1971, 1970, 1969, 1968, 1967, 1966, 1965, 1964, 1963, 1962, 1961, 1960, 1959, 1958, 1957, 1956, 1955, 1954, 1953, 1952, 1951, 1950, 1949, 1948, 1947, 1946, 1945, 1944, 1943, 1942, 1941, 1940, 1939, 1938, 1937, 1936, 1935, 1934, 1933, 1932, 1931, 1930, 1929, 1928, 1927, 1926, 1925, 1924, 1923, 1922, 1921, 1920)'), ('Profile.birth_day', 'Profile Day of birth: PositiveIntegerField (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31)'), ('Profile.birth_month', 'Profile Month of birth: PositiveIntegerField (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)'), ('Profile.call_on', 'Profile call_on: NullBooleanField '), ('Profile.challenge_on', 'Profile challenge_on: NullBooleanField '), ('Profile.city', 'Profile City/City part: CharField '), ('Profile.club_card_available', 'Profile Club card available: BooleanField '), ('Profile.club_card_dispatched', 'Profile Club card dispatched?: BooleanField '), ('Profile.correspondence_city', 'Profile City/City part: CharField '), ('Profile.correspondence_country', 'Profile Country: CharField '), ('Profile.correspondence_street', 'Profile Street and number: CharField '), ('Profile.correspondence_zip_code', 'Profile ZIP Code: CharField '), ('Profile.country', 'Profile Country: CharField '), ('Profile.created', 'Profile Date of creation: DateTimeField '), ('Profile.date_joined', 'Profile datum registrace: DateTimeField '), ('Profile.different_correspondence_address', 'Profile Different correspondence address: BooleanField '), ('Profile.email', 'Profile e-mailová adresa: CharField '), ('Profile.first_name', 'Profile křestní jméno: CharField '), ('Profile.id', 'Profile ID: AutoField '), ('Profile.is_active', 'Profile aktivní: BooleanField '), ('Profile.is_staff', 'Profile administrační přístup: BooleanField '), ('Profile.is_superuser', 'Profile superuživatel: BooleanField '), ('Profile.language', "Profile Language: CharField ('cs', 'en')"), ('Profile.last_login', 'Profile poslední přihlášení: DateTimeField '), ('Profile.last_name', 'Profile příjmení: CharField '), ('Profile.letter_on', 'Profile letter_on: NullBooleanField '), ('Profile.newsletter_on', 'Profile newsletter_on: NullBooleanField '), ('Profile.note', 'Profile Note for making a boring form more lively: TextField '), ('Profile.other_benefits', 'Profile Other benefits: TextField '), ('Profile.other_support', 'Profile Other support: TextField '), ('Profile.password', 'Profile heslo: CharField '), ('Profile.polymorphic_ctype', 'Profile polymorphic ctype: ForeignKey '), ('Profile.profile_picture', 'Profile Profile picture: FileField '), ('Profile.profile_text', 'Profile What is your reason?: TextField '), ('Profile.public', 'Profile Publish my name in the list of supporters: BooleanField '), ('Profile.send_mailing_lists', 'Profile Sending of mailing lists allowed: BooleanField '), ('Profile.street', 'Profile Street and number: CharField '), ('Profile.title_after', 'Profile Title after name: CharField '), ('Profile.title_before', 'Profile Title before name: CharField '), ('Profile.updated', 'Profile Date of last change: DateTimeField '), ('Profile.username', 'Profile uživatelské jméno: CharField '), ('Profile.zip_code', 'Profile ZIP Code: CharField '), ('User.date_joined', 'User datum registrace: DateTimeField '), ('User.email', 'User e-mailová adresa: CharField '), ('User.first_name', 'User křestní jméno: CharField '), ('User.id', 'User ID: AutoField '), ('User.is_active', 'User aktivní: BooleanField '), ('User.is_staff', 'User administrační přístup: BooleanField '), ('User.is_superuser', 'User superuživatel: BooleanField '), ('User.last_login', 'User poslední přihlášení: DateTimeField '), ('User.last_name', 'User příjmení: CharField '), ('User.password', 'User heslo: CharField '), ('User.username', 'User uživatelské jméno: CharField '), ('User.last_payment.BIC', 'User.last_payment BIC: CharField '), ('User.last_payment.KS', 'User.last_payment CS: CharField '), ('User.last_payment.SS', 'User.last_payment SS: CharField '), ('User.last_payment.VS', 'User.last_payment VS 1: CharField '), ('User.last_payment.VS2', 'User.last_payment VS 2: CharField '), ('User.last_payment.account', 'User.last_payment Account: CharField '), ('User.last_payment.account_name', 'User.last_payment Account name: CharField '), ('User.last_payment.account_statement', 'User.last_payment account statement: ForeignKey '), ('User.last_payment.amount', 'User.last_payment Amount: PositiveIntegerField '), ('User.last_payment.bank_code', 'User.last_payment Bank code: CharField '), ('User.last_payment.bank_name', 'User.last_payment Bank name: CharField '), ('User.last_payment.created', 'User.last_payment Date of creation: DateTimeField '), ('User.last_payment.currency', 'User.last_payment Currency: CharField '), ('User.last_payment.date', 'User.last_payment Date of payment: DateField '), ('User.last_payment.done_by', 'User.last_payment Done by: CharField '), ('User.last_payment.id', 'User.last_payment ID: AutoField '), ('User.last_payment.operation_id', 'User.last_payment Operation ID: CharField '), ('User.last_payment.order_id', 'User.last_payment Order ID: CharField '), ('User.last_payment.recipient_message', 'User.last_payment Recipient message: CharField '), ('User.last_payment.specification', 'User.last_payment Specification: CharField '), ('User.last_payment.transfer_note', 'User.last_payment Transfer note: CharField '), ('User.last_payment.transfer_type', 'User.last_payment Transfer type: CharField '), ('User.last_payment.type', "User.last_payment Typ: CharField ('bank-transfer', 'cash', 'expected', 'darujme')"), ('User.last_payment.updated', 'User.last_payment Date of last change: DateTimeField '), ('User.last_payment.user_donor_payment_channel', 'User.last_payment user donor payment channel: ForeignKey '), ('User.last_payment.user_identification', 'User.last_payment Sender identification: CharField '), ('User.source.direct_dialogue', 'User.source Is from Direct Dialogue: BooleanField '), ('User.source.id', 'User.source ID: AutoField '), ('User.source.name', 'User.source Název: CharField '), ('User.source.slug', 'User.source Slug: SlugField '), ('UserInCampaign.activity_points', 'UserInCampaign Activity points: IntegerField '), ('UserInCampaign.additional_information', 'UserInCampaign Additional information: TextField '), ('UserInCampaign.campaign', 'UserInCampaign campaign: ForeignKey '), ('UserInCampaign.created', 'UserInCampaign Date of creation: DateTimeField '), ('UserInCampaign.email_confirmed', 'UserInCampaign Is confirmed via e-mail: BooleanField '), ('UserInCampaign.exceptional_membership', 'UserInCampaign Exceptional membership: BooleanField '), ('UserInCampaign.expected_date_of_first_payment', 'UserInCampaign Expected date of first payment: DateField '), ('UserInCampaign.field_of_work', 'UserInCampaign Field of work: CharField '), ('UserInCampaign.gdpr_consent', 'UserInCampaign GDPR consent: BooleanField '), ('UserInCampaign.id', 'UserInCampaign ID: AutoField '), ('UserInCampaign.knows_us_from', 'UserInCampaign Where does he/she know us from?: CharField '), ('UserInCampaign.next_communication_date', 'UserInCampaign Date of next communication: DateField '), ('UserInCampaign.next_communication_method', "UserInCampaign Method of next communication: CharField ('email', 'phonecall', 'mail', 'personal', 'internal')"), ('UserInCampaign.note', 'UserInCampaign Note for making a boring form more lively: TextField '), ('UserInCampaign.old_account', 'UserInCampaign Old account: BooleanField '), ('UserInCampaign.other_support', 'UserInCampaign Other support: TextField '), ('UserInCampaign.public', 'UserInCampaign Publish my name in the list of supporters/petitents of this campaign: BooleanField '), ('UserInCampaign.recruiter', 'UserInCampaign recruiter: ForeignKey '), ('UserInCampaign.registered_support', 'UserInCampaign Registered support: DateTimeField '), ('UserInCampaign.regular_amount', 'UserInCampaign Regularly (amount): PositiveIntegerField '), ('UserInCampaign.regular_frequency', "UserInCampaign Frequency of regular payments: CharField ('monthly', 'quaterly', 'biannually', 'annually', None)"), ('UserInCampaign.regular_payments', "UserInCampaign Regular payments: CharField ('regular', 'onetime', 'promise')"), ('UserInCampaign.source', 'UserInCampaign Source: ForeignKey '), ('UserInCampaign.updated', 'UserInCampaign Date of last change: DateTimeField '), ('UserInCampaign.userprofile', 'UserInCampaign userprofile: ForeignKey '), ('UserInCampaign.variable_symbol', 'UserInCampaign Variable symbol: CharField '), ('UserInCampaign.verified', 'UserInCampaign Verified: BooleanField '), ('UserInCampaign.verified_by', 'UserInCampaign Verified by: ForeignKey '), ('UserInCampaign.why_supports', 'UserInCampaign Why does he/she support us?: TextField '), ('UserInCampaign.wished_information', 'UserInCampaign Send regular news via email: BooleanField '), ('UserInCampaign.wished_tax_confirmation', 'UserInCampaign Send tax confirmation: BooleanField '), ('UserInCampaign.wished_welcome_letter', 'UserInCampaign Send welcome letter: BooleanField '), ('action', "Operace: CharField ('daily', 'new-user', 'new-payment')")], help_text='Value or variable on left-hand side', max_length=50, null=True, verbose_name='Variable'),
        ),
        migrations.AlterField(
            model_name='userincampaign',
            name='userprofile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='aklub.Profile'),
        ),
        migrations.AlterField(
            model_name='userincampaign',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_users', to='aklub.Profile', verbose_name='Verified by'),
        ),
    ]
