# Generated by Django 2.2.4 on 2019-08-05 04:01

from django.contrib.auth import get_user_model
from django.db import migrations

from .data_migration.fix_advanced_filters_app_table_column import (
    forwards_func, reverse_func)


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0036_update_profile_model_dependency_models'),
    ]
    
    operations = [
        # Change column name from old UserProfile db model to the new Profile db model for 'advanced_filter' app
        migrations.RunPython(forwards_func, reverse_func),
    ]
