# Generated by Django 2.2.4 on 2019-08-23 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0036_update_profile_model_dependency_models'),
    ]

    operations = [
    ]
