# Generated by Django 2.2.4 on 2019-08-05 04:01

from django.contrib.auth import get_user_model
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0036_update_profile_model_dependency_models'),
    ]
    
    operations = [
        # Change column name from old UserProfile db model to the new Profile db model for 'advanced_filter' app
        migrations.RunSQL("ALTER TABLE advanced_filters_advancedfilter_users RENAME userprofile_id TO {}_id".format(get_user_model()._meta.model_name)),
    ]
