# Generated by Django 2.2.4 on 2019-08-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0036_auto_20190821_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='crn',
            field=models.CharField(default='00000000', max_length=20, verbose_name='Company Registration Number'),
            preserve_default=False,
        ),
    ]
