# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0037_auto_20161107_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name of result')),
                ('sort', models.CharField(choices=[('promise', 'Promise'), ('ongoing', 'Ongoing communication'), ('dont_contact', "Don't contact again")], default='individual', max_length=30, verbose_name='Sort of result')),
            ],
        ),
        migrations.AlterModelOptions(
            name='userincampaign',
            options={'ordering': ['userprofile__user__last_name', 'userprofile__user__first_name'], 'verbose_name': 'User in campaign', 'verbose_name_plural': 'Users in campaign'},
        ),
        migrations.AddField(
            model_name='userincampaign',
            name='next_communication_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of next communication'),
        ),
        migrations.AddField(
            model_name='userincampaign',
            name='next_communication_method',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('phonecall', 'Phonecall'), ('mail', 'Mail'), ('personal', 'Personal'), ('internal', 'Internal')], max_length=30, null=True, verbose_name='Method of next communication'),
        ),
        migrations.AlterField(
            model_name='terminalcondition',
            name='variable',
            field=models.CharField(blank=True, choices=[('User.date_joined', 'User datum registrace: DateTimeField '), ('User.email', 'User e-mailová adresa: CharField '), ('User.first_name', 'User křestní jméno: CharField '), ('User.id', 'User ID: AutoField '), ('User.is_active', 'User aktivní: BooleanField '), ('User.is_staff', 'User administrační přístup: BooleanField '), ('User.is_superuser', 'User superuživatel: BooleanField '), ('User.last_login', 'User poslední přihlášení: DateTimeField '), ('User.last_name', 'User příjmení: CharField '), ('User.password', 'User heslo: CharField '), ('User.username', 'User uživatelské jméno: CharField '), ('User.last_payment.BIC', 'User.last_payment BIC: CharField '), ('User.last_payment.KS', 'User.last_payment KS: CharField '), ('User.last_payment.SS', 'User.last_payment SS: CharField '), ('User.last_payment.VS', 'User.last_payment VS: CharField '), ('User.last_payment.account', 'User.last_payment Account: CharField '), ('User.last_payment.account_name', 'User.last_payment Jméno účtu: CharField '), ('User.last_payment.account_statement', 'User.last_payment account statement: ForeignKey '), ('User.last_payment.amount', 'User.last_payment Částka: PositiveIntegerField '), ('User.last_payment.bank_code', 'User.last_payment Kód banky: CharField '), ('User.last_payment.bank_name', 'User.last_payment Jméno banky: CharField '), ('User.last_payment.currency', 'User.last_payment Měna: CharField '), ('User.last_payment.date', 'User.last_payment Datum platby: DateField '), ('User.last_payment.done_by', 'User.last_payment Provedl: CharField '), ('User.last_payment.id', 'User.last_payment ID: AutoField '), ('User.last_payment.operation_id', 'User.last_payment ID Operace: CharField '), ('User.last_payment.order_id', 'User.last_payment ID objednávky: CharField '), ('User.last_payment.recipient_message', 'User.last_payment Zpráva pro recipienta: CharField '), ('User.last_payment.specification', 'User.last_payment Specifikace: CharField '), ('User.last_payment.transfer_note', 'User.last_payment Poznámka k převodu: CharField '), ('User.last_payment.transfer_type', 'User.last_payment Typ převodu: CharField '), ('User.last_payment.type', "User.last_payment Typ: CharField ('bank-transfer', 'cash', 'expected', 'darujme')"), ('User.last_payment.user', 'User.last_payment user: ForeignKey '), ('User.last_payment.user_identification', 'User.last_payment Identifikace odesílatele: CharField '), ('User.source.direct_dialogue', 'User.source Pochází z Direct dialogu: BooleanField '), ('User.source.id', 'User.source ID: AutoField '), ('User.source.name', 'User.source Jméno: CharField '), ('User.source.slug', 'User.source Identifikátor: SlugField '), ('UserInCampaign.activity_points', 'UserInCampaign Body za aktivitu: IntegerField '), ('UserInCampaign.additional_information', 'UserInCampaign Rozšiřující informace: TextField '), ('UserInCampaign.campaign', 'UserInCampaign campaign: ForeignKey '), ('UserInCampaign.end_of_regular_payments', 'UserInCampaign Konec pravidelných plateb (pro platby kartou): DateField '), ('UserInCampaign.exceptional_membership', 'UserInCampaign Výjimečné členství: BooleanField '), ('UserInCampaign.expected_date_of_first_payment', 'UserInCampaign Očekávané datum první platby: DateField '), ('UserInCampaign.expected_regular_payment_date', 'UserInCampaign expected regular payment date: DateField '), ('UserInCampaign.extra_money', 'UserInCampaign extra money: IntegerField '), ('UserInCampaign.field_of_work', 'UserInCampaign Pracovní oblast: CharField '), ('UserInCampaign.id', 'UserInCampaign ID: AutoField '), ('UserInCampaign.knows_us_from', 'UserInCampaign Odkud nás zná?: CharField '), ('UserInCampaign.last_payment', 'UserInCampaign last payment: DenormDBField '), ('UserInCampaign.next_communication_date', 'UserInCampaign Datum příští komunikace komunikace: DateField '), ('UserInCampaign.next_communication_method', "UserInCampaign Metoda příští komunikace: CharField ('email', 'phonecall', 'mail', 'personal', 'internal')"), ('UserInCampaign.no_upgrade', 'UserInCampaign no upgrade: NullBooleanField '), ('UserInCampaign.note', 'UserInCampaign Poznámka pro oživení nudného formuláře: TextField '), ('UserInCampaign.number_of_payments', 'UserInCampaign number of payments: IntegerField '), ('UserInCampaign.old_account', 'UserInCampaign Starý účet: BooleanField '), ('UserInCampaign.other_support', 'UserInCampaign Jiná podpora: TextField '), ('UserInCampaign.payment_total', 'UserInCampaign payment total: FloatField '), ('UserInCampaign.recruiter', 'UserInCampaign recruiter: ForeignKey '), ('UserInCampaign.registered_support', 'UserInCampaign Registrace podpory: DateTimeField '), ('UserInCampaign.regular_amount', 'UserInCampaign Částka pravidelné platby: PositiveIntegerField '), ('UserInCampaign.regular_frequency', "UserInCampaign Frekvence pravidelných plateb: CharField ('monthly', 'quaterly', 'biannually', 'annually', None)"), ('UserInCampaign.regular_payments', "UserInCampaign Pravidelné platby: CharField ('regular', 'onetime', 'promise')"), ('UserInCampaign.source', 'UserInCampaign Zdroj: ForeignKey '), ('UserInCampaign.updated', 'UserInCampaign Datum poslední změny: DateTimeField '), ('UserInCampaign.userprofile', 'UserInCampaign userprofile: ForeignKey '), ('UserInCampaign.variable_symbol', 'UserInCampaign Variabilní symbol: CharField '), ('UserInCampaign.verified', 'UserInCampaign Ověřen: BooleanField '), ('UserInCampaign.verified_by', 'UserInCampaign Ověřil: ForeignKey '), ('UserInCampaign.why_supports', 'UserInCampaign Proč nás podporuje?: TextField '), ('UserInCampaign.wished_information', 'UserInCampaign Zasílat pravidelné informace emailem: BooleanField '), ('UserInCampaign.wished_tax_confirmation', 'UserInCampaign Zaslat daňové potvrzení (na konci roku): BooleanField '), ('UserInCampaign.wished_welcome_letter', 'UserInCampaign Odeslat uvítací dopis s členskou kartou: BooleanField '), ('UserProfile.addressment', 'UserProfile Oslovení v dopise: CharField '), ('UserProfile.addressment_on_envelope', 'UserProfile Oslovení na obálku: CharField '), ('UserProfile.city', 'UserProfile Město/Městská část: CharField '), ('UserProfile.club_card_available', 'UserProfile Nárok na klubovou kartu: BooleanField '), ('UserProfile.club_card_dispatched', 'UserProfile Klubová karta odeslána?: BooleanField '), ('UserProfile.country', 'UserProfile Země: CharField '), ('UserProfile.created', 'UserProfile Datum vytvoření: DateTimeField '), ('UserProfile.different_correspondence_address', 'UserProfile Jiná korespondenční adresa: BooleanField '), ('UserProfile.id', 'UserProfile ID: AutoField '), ('UserProfile.language', "UserProfile Jazyk: CharField ('cs', 'en')"), ('UserProfile.note', 'UserProfile Poznámka pro oživení nudného formuláře: TextField '), ('UserProfile.other_benefits', 'UserProfile Další benefity: TextField '), ('UserProfile.other_support', 'UserProfile Jiná podpora: TextField '), ('UserProfile.profile_picture', 'UserProfile Profilová fotografie: FileField '), ('UserProfile.profile_text', 'UserProfile A jaký je Tvůj důvod?: TextField '), ('UserProfile.public', 'UserProfile Zveřejnit mé jméno v seznamu podporovatelů: BooleanField '), ('UserProfile.sex', "UserProfile Pohlaví: CharField ('male', 'female', 'unknown')"), ('UserProfile.street', 'UserProfile Ulice a číslo domu (č.p./č.o.): CharField '), ('UserProfile.telephone', 'UserProfile Telefon: CharField '), ('UserProfile.title_after', 'UserProfile Titul za jménem: CharField '), ('UserProfile.title_before', 'UserProfile Titul před jménem: CharField '), ('UserProfile.updated', 'UserProfile Datum poslední změny: DateTimeField '), ('UserProfile.user', 'UserProfile user: OneToOneField '), ('UserProfile.zip_code', 'UserProfile PSČ: TextField '), ('action', "Akce: CharField ('daily', 'new-user', 'new-payment')")], help_text='Value or variable on left-hand side', max_length=50, null=True, verbose_name='Variable'),
        ),
        migrations.AlterField(
            model_name='userincampaign',
            name='campaign',
            field=models.ForeignKey(default=None, help_text='Campaign', on_delete=django.db.models.deletion.CASCADE, to='aklub.Campaign'),
        ),
        migrations.AlterField(
            model_name='userincampaign',
            name='regular_frequency',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quaterly', 'Quaterly'), ('biannually', 'Bianually'), ('annually', 'Anually'), (None, 'Onetime')], max_length=20, null=True, verbose_name='Frequency of regular payments'),
        ),
        migrations.AlterField(
            model_name='userincampaign',
            name='regular_payments',
            field=models.CharField(choices=[('regular', 'Regular payments'), ('onetime', 'No regular payments'), ('promise', 'Promise of regular payments')], default='onetime', help_text='Is this user registered for regular payments?', max_length=20, verbose_name='Regular payments'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='result',
            field=models.ManyToManyField(blank=True, null=True, to='aklub.Result', verbose_name='Acceptable results of communication'),
        ),
        migrations.AddField(
            model_name='communication',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aklub.Result', verbose_name='Result of communication'),
        ),
    ]
