# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0037_auto_20160921_1533'),
        ('aklub', '0036_auto_20160917_1001'),
    ]

    operations = [
    ]
