# Generated by Django 2.2.4 on 2019-08-26 20:30

from django.db import migrations

from .data_migration.fix_advanced_filters_app_table_column import forwards_func, reverse_func


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0038_auto_20190826_1947'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
