# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-12 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0042_auto_20170117_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condition',
            options={'ordering': ('name',), 'verbose_name': 'Condition', 'verbose_name_plural': 'Conditions'},
        ),
        migrations.AlterField(
            model_name='automaticcommunication',
            name='subject',
            field=models.CharField(max_length=130, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='automaticcommunication',
            name='subject_en',
            field=models.CharField(blank=True, max_length=130, null=True, verbose_name='English subject'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='subject',
            field=models.CharField(help_text='The topic of this communication', max_length=130, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='masscommunication',
            name='subject',
            field=models.CharField(max_length=130, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='masscommunication',
            name='subject_en',
            field=models.CharField(blank=True, help_text='English version of the subject. If empty, English speaking users will not receive this communication.', max_length=130, null=True, verbose_name='English subject'),
        ),
        migrations.AlterField(
            model_name='userincampaign',
            name='regular_payments',
            field=models.CharField(choices=[('regular', 'Regular payments'), ('onetime', 'No regular payments'), ('promise', 'Promise of regular payments')], help_text='Is this user registered for regular payments?', max_length=20, verbose_name='Regular payments'),
        ),
    ]
