# Generated by Django 2.2.4 on 2019-09-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0042_auto_20190909_0912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userincampaign',
            options={'ordering': ['userprofile__userprofile__last_name', 'userprofile__userprofile__first_name', 'userprofile__companyprofile__name'], 'verbose_name': 'User in campaign', 'verbose_name_plural': 'Users in campaign'},
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='tin',
            field=models.CharField(max_length=20, null=True, verbose_name='Tax Identification Number'),
        ),
    ]
