# Generated by Django 2.2.4 on 2019-09-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0043_auto_20190909_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='name',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='Company name'),
        ),
    ]
