# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0043_auto_20170612_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='darujme_project_id',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Darujme.cz project ID'),
        ),
    ]
