# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-20 15:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
from django.db import transaction


@transaction.atomic
def populate_userprofile(apps, schema_editor):
    settings.AUTH_USER_MODEL = 'auth.User'
    Communication = apps.get_model("aklub", "Communication")
    User = apps.get_model("auth", "User")
    UserProfile = apps.get_model("aklub", "UserProfile")
    UserInCampaign = apps.get_model("aklub", "UserInCampaign")

    for user in User.objects.filter(userprofile=None):
        UserProfile.objects.create(user=user)

    for communication in Communication.objects.all():
        if communication.created_by:
            communication.created_by_profile = communication.created_by.userprofile
        if communication.handled_by:
            communication.handled_by_profile = communication.handled_by.userprofile
        communication.save()

    for user_in_campaign in UserInCampaign.objects.all():
        if user_in_campaign.verified_by:
            user_in_campaign.verified_by_profile = user_in_campaign.verified_by.userprofile
        user_in_campaign.save()

    for user_profile in UserProfile.objects.all():
        for field in user_profile.user._meta.fields:
            if field.name not in 'id':
                setattr(user_profile, field.name, getattr(user_profile.user, field.name))
        user_profile.save()

class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0045_auto_20171020_1506'),
    ]

    operations = [
        migrations.RunPython(populate_userprofile, migrations.RunPython.noop)
    ]
