# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-20 15:10
from __future__ import unicode_literals

from django_bulk_update.helper import bulk_update

from django.conf import settings
from django.db import connection
from django.db import migrations
from django.db import transaction


@transaction.atomic
def populate_userprofile(apps, schema_editor):
    settings.AUTH_USER_MODEL = 'auth.User'
    Communication = apps.get_model("aklub", "Communication")
    User = apps.get_model("auth", "User")
    UserProfile = apps.get_model("aklub", "UserProfile")
    UserInCampaign = apps.get_model("aklub", "UserInCampaign")

    for user in User.objects.filter(userprofile=None):
        UserProfile.objects.create(user=user)

    communications = Communication.objects.only('created_by', 'handled_by')
    for communication in communications:
        if communication.created_by:
            communication.created_by_profile = communication.created_by.userprofile
        if communication.handled_by:
            communication.handled_by_profile = communication.handled_by.userprofile
    bulk_update(communications, batch_size=1000)

    users_in_campaign = UserInCampaign.objects.all()
    for user_in_campaign in users_in_campaign:
        if user_in_campaign.verified_by:
            user_in_campaign.verified_by_profile = user_in_campaign.verified_by.userprofile
    bulk_update(users_in_campaign, batch_size=1000)

    user_profiles = UserProfile.objects.all()
    for user_profile in user_profiles:
        for field in user_profile.user._meta.fields:
            if field.name not in 'id':
                setattr(user_profile, field.name, getattr(user_profile.user, field.name))

        cursor = connection.cursor()
        cursor.execute("select group_id from auth_user_groups where user_id='%s'" % user_profile.user.id)
        row = cursor.fetchone()
        while row:
            user_profile.groups.add(row[0])
            row = cursor.fetchone()

        cursor.execute("select permission_id from auth_user_user_permissions where user_id='%s'" % user_profile.user.id)
        row = cursor.fetchone()
        while row:
            user_profile.user_permissions.add(row[0])
            row = cursor.fetchone()
    bulk_update(user_profiles, batch_size=1000)

class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0045_auto_20171020_1506'),
    ]

    operations = [
        migrations.RunPython(populate_userprofile, migrations.RunPython.noop)
    ]
