# Generated by Django 2.2.6 on 2019-10-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0047_auto_20190919_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='masscommunication',
            name='template_en_name',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Choose template'),
        ),
        migrations.AddField(
            model_name='masscommunication',
            name='template_en_type',
            field=models.CharField(blank=True, choices=[('new', 'Create new email body'), ('existed', 'Choose email body template')], default='new', max_length=350, verbose_name='Choose how to create an email body'),
        ),
        migrations.AddField(
            model_name='masscommunication',
            name='template_name',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Choose template'),
        ),
        migrations.AddField(
            model_name='masscommunication',
            name='template_type',
            field=models.CharField(blank=True, choices=[('new', 'Create new email body'), ('existed', 'Choose email body template')], default='new', max_length=350, verbose_name='Choose how to create an email body'),
        ),
        migrations.AlterField(
            model_name='accountstatements',
            name='type',
            field=models.CharField(choices=[('account', 'Account statement - Fio Banka'), ('account_cs', 'Account statement - Česká spořitelna'), ('account_kb', 'Account statement - Komerční Banka'), ('account_csob', 'Account statement - ČSOB'), ('account_sberbank', 'Account statement - Sberbank'), ('darujme', 'Darujme.cz')], max_length=20),
        ),
    ]
