# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-21 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0047_auto_20171020_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communication',
            old_name='created_by_profile',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='communication',
            old_name='handled_by_profile',
            new_name='handled_by',
        ),
        migrations.RenameField(
            model_name='userincampaign',
            old_name='verified_by_profile',
            new_name='verified_by',
        ),
    ]
