# Generated by Django 2.2.6 on 2019-10-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0048_auto_20191022_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='contact_first_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Contact first name'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='contact_last_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Contact last name'),
        ),
    ]
