# Generated by Django 2.2.6 on 2019-10-22 13:47

from django.db import migrations, models, connection
from aklub.models import BankAccount


class Migration(migrations.Migration):
    def delete_all_bankaccounts(apps, schema_editor):
        with connection.cursor() as cursor:
            cursor.execute("UPDATE aklub_donorpaymentchannel set bank_account_id = NULL")
            cursor.execute("DELETE from aklub_bankaccount")

    dependencies = [
        ('aklub', '0049_auto_20191022_1547'),
    ]

    operations = [
        migrations.RunPython(delete_all_bankaccounts),
    ]
