# Generated by Django 2.2.6 on 2019-10-24 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0049_auto_20191014_1320'),
        ('aklub', '0049_auto_20191022_1547'),
    ]

    operations = [
    ]
