# Generated by Django 2.2.6 on 2019-10-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0051_auto_20191024_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyaccount',
            name='slug',
            field=models.SlugField(blank=True, default=None, help_text='Identifier of the Account', max_length=100, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
