# Generated by Django 2.2.6 on 2019-10-16 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0051_auto_20191024_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='darujme_api_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='darujme_api_secret',
        ),
        migrations.RemoveField(
            model_name='event',
            name='darujme_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='darujme_project_id',
        ),
    ]
