# Generated by Django 2.2.6 on 2019-11-07 08:36

import aklub.autocom
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0053_moneyaccount_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorpaymentchannel',
            name='money_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moneyaccounts', to='aklub.MoneyAccount'),
        ),
    ]
