# Generated by Django 2.2.7 on 2019-11-14 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0054_auto_20191107_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masscommunication',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='profileemail',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='taxconfirmationfield',
            name='field',
            field=models.CharField(max_length=36, verbose_name='field'),
        ),
        migrations.AlterField(
            model_name='taxconfirmationpdf',
            name='obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aklub.TaxConfirmation'),
        ),
    ]
