# Generated by Django 2.2.7 on 2019-11-17 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0050_merge_20191024_0859'),
        ('aklub', '0055_auto_20191114_1203'),
    ]

    operations = [
    ]
