# Generated by Django 2.2.7 on 2019-11-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0055_auto_20191114_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
