# Generated by Django 2.2.8.dev20191120135045 on 2019-11-20 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0056_merge_20191117_0649'),
        ('aklub', '0056_auto_20191119_1234'),
    ]

    operations = [
    ]
