# Generated by Django 2.2.8 on 2020-01-02 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0057_auto_20191212_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxconfirmation',
            name='administrative_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aklub.AdministrativeUnit', verbose_name='administrative unit'),
        ),
    ]
