# Generated by Django 2.2.9 on 2020-01-14 10:30

import aklub.autocom
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0060_auto_20200108_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxconfirmation',
            name='user_profile',
            field=models.ForeignKey(blank=False, null=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
