# Generated by Django 2.2.8.dev20191120135045 on 2020-01-14 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0057_merge_20191120_1732'),
        ('aklub', '0060_auto_20200108_0907'),
    ]

    operations = [
    ]
