# Generated by Django 2.2.9 on 2020-01-09 08:31
import django.core.validators
from django.db import migrations, models

from aklub.models import AdministrativeUnit, MoneyAccount, AccountStatements, Preference, TaxConfirmation

class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0061_auto_20200114_1130'),
    ]

    def default_values_money_acccount(apps, schema_editor):
        for obj in MoneyAccount.objects.all():
            if not hasattr(obj, 'administrative_unit'):
                unit, _ = AdministrativeUnit.objects.get_or_create(name='change_this_unit_then_delete')
                obj.administrative_unit = unit
                obj.save()

    def default_values_preference(apps, schema_editor):
        for obj in Preference.objects.all():
            if not hasattr(obj, 'administrative_unit'):
                unit, _ = AdministrativeUnit.objects.get_or_create(name='change_this_unit_then_delete')
                obj.administrative_unit = unit
                obj.save()

    def default_values_taxconfirmation(apps, schema_editor):
        for obj in TaxConfirmation.objects.all():
            if not hasattr(obj, 'administrative_unit'):
                unit, _ = AdministrativeUnit.objects.get_or_create(name='change_this_unit_then_delete')
                obj.administrative_unit = unit
                obj.save()



    operations = [
        migrations.RunPython(default_values_money_acccount),
        migrations.RunPython(default_values_preference),
        migrations.RunPython(default_values_taxconfirmation),

        migrations.AlterField(
            model_name='moneyaccount',
            name='administrative_unit',
            field=models.ForeignKey(null=False, blank=False, on_delete=django.db.models.deletion.CASCADE, to='aklub.AdministrativeUnit', verbose_name='administrative unit'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='administrative_unit',
            field=models.ForeignKey(null=False, blank=False, on_delete=django.db.models.deletion.CASCADE, to='aklub.AdministrativeUnit', verbose_name='administrative unit'),
        ),
        migrations.AlterField(
            model_name='taxconfirmation',
            name='administrative_unit',
            field=models.ForeignKey(null=False, blank=False, on_delete=django.db.models.deletion.CASCADE, to='aklub.AdministrativeUnit', verbose_name='administrative unit'),
        ),

    ]
