# Generated by Django 2.2.8.dev20191120135045 on 2020-01-14 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0057_merge_20191120_1732'),
        ('aklub', '0062_auto_20200109_09110'),
    ]

    operations = [
    ]
