# Generated by Django 2.2.9 on 2020-01-15 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0063_auto_20200114_1732'),
        ('aklub', '0063_merge_20200114_2108'),
    ]

    operations = [
    ]
