# Generated by Django 2.2.9 on 2020-01-28 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0064_auto_20200128_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='automaticcommunication',
            name='administrative_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aklub.AdministrativeUnit', verbose_name='administrative unit'),
        ),
    ]
