# Generated by Django 2.2.10 on 2020-02-27 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smmapdfs', '0003_auto_20191126_1611'),
        ('aklub', '0066_auto_20200128_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxconfirmation',
            name='pdf_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smmapdfs.PdfSandwichType'),
        ),
    ]
