# Generated by Django 2.2.10 on 2020-03-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0066_auto_20200128_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativeunit',
            name='slug',
            field=models.SlugField(default=None, help_text='Identifier of the administrative unit', max_length=100, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='profile',
            name='unsubscribe_token',
            field=models.CharField(blank=True, max_length=180, null=True, unique=True, verbose_name='unsubscribe token'),
        ),
    ]
