# Generated by Django 2.2.9 on 2020-02-03 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0066_auto_20200128_1502'),
        ('aklub', '0064_merge_20200115_1345'),
    ]

    operations = [
    ]
