# Generated by Django 2.2.10 on 2020-03-04 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0067_taxconfirmation_pdf_type'),
    ]
    def taxconfirmation_type(apps, schema_editor):
        db_alias = schema_editor.connection.alias
        AdministrativeUnit = apps.get_model("aklub", "AdministrativeUnit")
        TaxConfirmation = apps.get_model("aklub", "TaxConfirmation")
        PdfSandwichType = apps.get_model('smmapdfs','PdfSandwichType')
        for unit in AdministrativeUnit.objects.using(db_alias).all():
            try:
                pdf_type = PdfSandwichType.objects.using(db_alias).get(pdfsandwichtypeconnector__administrative_unit=unit)
            except PdfSandwichType.DoesNotExist:
                continue
            taxs = TaxConfirmation.objects.using(db_alias).filter(administrative_unit=unit)
            taxs.update(pdf_type=pdf_type)




    operations = [
            migrations.RunPython(taxconfirmation_type, reverse_code=migrations.RunPython.noop),
    ]
