# Generated by Django 2.2.10 on 2020-03-19 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0067_auto_20200221_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('can_edit_all_units', 'Může editovat všechno ve všech administrativních jednotkách'), ('can_remove_contact_from_administrative_unit', 'Can remove contact from his administrative unit')), 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
