# Generated by Django 2.2.10 on 2020-04-06 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0067_merge_20200203_0833'),
        ('aklub', '0068_auto_20200319_1414'),
    ]

    operations = [
    ]
