# Generated by Django 2.2.9 on 2020-01-30 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0070_auto_20200206_1428'),
    ]

    def default_data_migration_mass_auto(apps, schema_editor):
        # fill new method_type field in autoc and mass communication
        db_alias = schema_editor.connection.alias
        InteractionType = apps.get_model("interactions", "InteractionType")

        mass_email_type = InteractionType.objects.using(db_alias).get(slug='email-mass')
        email_type = InteractionType.objects.using(db_alias).get(slug='email-auto')

        MassCommunication = apps.get_model("aklub", "MassCommunication")
        AutomaticCommunication = apps.get_model("aklub", "AutomaticCommunication")

        mass_data = MassCommunication.objects.using(db_alias).all()
        automatic_data = AutomaticCommunication.objects.using(db_alias).all()

        mass_data.update(method_type=mass_email_type)
        automatic_data.update(method_type=email_type)

        for mass_item in mass_data:
            mass_item.save()

        for auto_item in automatic_data:
            auto_item.save()




    operations = [
        migrations.RunPython(default_data_migration_mass_auto, reverse_code=migrations.RunPython.noop),

    ]
