# Generated by Django 2.2.9 on 2020-02-06 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0005_auto_20200206_1311'),
        ('aklub', '0070_delete_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='automaticcommunication',
            name='method_type',
            field=models.ForeignKey(default='', limit_choices_to=models.Q(('send_sms', True), ('send_email', True), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='interactions.InteractionType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='masscommunication',
            name='method_type',
            field=models.ForeignKey(default='', limit_choices_to=models.Q(('send_sms', True), ('send_email', True), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='interactions.InteractionType'),
            preserve_default=False,
        ),
    ]
