# Generated by Django 2.2.10 on 2020-04-14 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0073_auto_20200206_1440'),
        ('aklub', '0069_merge_20200406_0617'),
    ]

    operations = [
    ]
