# Generated by Django 2.2.12 on 2020-04-30 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0074_auto_20200417_1112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserYearPayments',
        ),
    ]
