# Generated by Django 2.2.12 on 2020-04-21 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0074_auto_20200417_1112'),
        ('aklub', '0074_merge_20200414_0547'),
    ]

    operations = [
    ]
