# Generated by Django 2.2.10 on 2020-02-27 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smmapdfs', '0003_auto_20191126_1611'),
        ('aklub', '0075_delete_useryearpayments'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxconfirmation',
            name='pdf_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smmapdfs.PdfSandwichType'),
        ),
        migrations.AddField(
            model_name='masscommunication',
            name='attached_tax_confirmation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smmapdfs.PdfSandwichType', verbose_name='Type of PDF'),
        ),
        migrations.AddField(
            model_name='masscommunication',
            name='attached_tax_confirmation_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='masscommunication',
            name='attach_tax_confirmation',
            field=models.BooleanField(default=False, help_text='If this field is checked, select year and type of pdf to send', verbose_name='Attach tax confirmation'),
        ),
    ]
