# Generated by Django 2.2.12 on 2020-05-11 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0075_delete_useryearpayments'),
        ('aklub', '0075_merge_20200421_0651'),
    ]

    operations = [
    ]
