# Generated by Django 2.2.10 on 2020-03-04 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0077_auto_20200304_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxconfirmation',
            name='administrative_unit',
        ),
    ]
