# Generated by Django 2.2.12 on 2020-06-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0078_remove_taxconfirmation_administrative_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountstatements',
            name='pair_log',
            field=models.TextField(blank=True, help_text='Why Payment was not paired', verbose_name='Payment pairing log'),
        ),
    ]
