# Generated by Django 2.2.12 on 2020-05-14 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0078_remove_taxconfirmation_administrative_unit'),
        ('aklub', '0076_merge_20200511_0622'),
    ]

    operations = [
    ]
