# Generated by Django 2.2.12 on 2020-05-21 09:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion

 # not ideal, but there is no easy way to do it in other way
 # cuz of contenttype (well hope we dont change it in future)
from aklub.models import Profile, CompanyContact, ProfileEmail

class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0078_remove_taxconfirmation_administrative_unit'),
    ]
    operations = [
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_first_name', models.CharField(blank=True, max_length=256, verbose_name='Contact first name')),
                ('contact_last_name', models.CharField(blank=True, max_length=256, verbose_name='Contact last name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address')),
                ('telephone', models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator('^\\+?(42(0|1){1})?\\s?\\d{3}\\s?\\d{3}\\s?\\d{3}$', 'Telephone must consist of numbers, spaces and + sign or maximum number count is higher.')], verbose_name='Telephone number')),
                ('is_primary', models.NullBooleanField(choices=[(None, 'No'), (True, 'Yes')], default=None, verbose_name='Primary contact')),
                ('note', models.CharField(blank=True, max_length=70, verbose_name='Note')),
                ('administrative_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aklub.AdministrativeUnit', verbose_name='administrative unit')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aklub.CompanyProfile')),
            ],
        ),
        migrations.AlterField(
            model_name='profileemail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aklub.UserProfile'),
        ),
        migrations.AlterField(
            model_name='telephone',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aklub.UserProfile'),
        ),

    ]
