# Generated by Django 2.2.12 on 2020-07-01 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0079_merge_20200514_0604'),
        ('aklub', '0079_accountstatements_pair_log'),
    ]

    operations = [
    ]
