# Generated by Django 2.2.12 on 2020-06-25 10:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0079_accountstatements_pair_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='variable_symbol_prefix',
            field=models.PositiveIntegerField(blank=True, help_text='Number between 10000-99999', null=True, validators=[django.core.validators.MinValueValidator(10000), django.core.validators.MaxValueValidator(99999)], verbose_name='Variable_symbol_prefix'),
        ),
        migrations.AlterField(
            model_name='donorpaymentchannel',
            name='event',
            field=models.ForeignKey(help_text='Event', null=True, on_delete=django.db.models.deletion.CASCADE, to='aklub.Event', verbose_name='Event'),
        ),
    ]
