# Generated by Django 2.2.12 on 2020-06-11 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0080_auto_20200611_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileemail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aklub.UserProfile'),
        ),
        migrations.AlterField(
            model_name='telephone',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aklub.UserProfile'),
        ),
    ]
