# Generated by Django 2.2.12 on 2020-07-06 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0080_merge_20200701_1411'),
        ('aklub', '0080_auto_20200625_1216'),
    ]

    operations = [
    ]
