# Generated by Django 2.2.14 on 2020-07-22 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0081_auto_20200611_1000'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='companyprofile',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='profile',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
            ],
        ),
    ]
