# Generated by Django 2.2.12 on 2020-06-11 08:15

import django.core.validators
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0081_auto_20200611_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_first_name', models.CharField(blank=True, max_length=256, verbose_name='Contact first name')),
                ('contact_last_name', models.CharField(blank=True, max_length=256, verbose_name='Contact last name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address')),
                ('telephone', models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator('^\\+?(42(0|1){1})?\\s?\\d{3}\\s?\\d{3}\\s?\\d{3}$', 'Telephone must consist of numbers, spaces and + sign or maximum number count is higher.')], verbose_name='Telephone number')),
                ('is_primary', models.NullBooleanField(choices=[(None, 'No'), (True, 'Yes')], default=None, verbose_name='Primary contact')),
                ('note', models.CharField(blank=True, max_length=70, verbose_name='Note')),
                ('administrative_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aklub.AdministrativeUnit', verbose_name='administrative unit')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aklub.CompanyProfile')),
            ],
            options={
                'unique_together': {('is_primary', 'administrative_unit', 'email'), ('is_primary', 'administrative_unit', 'company')},
            },
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='contact_first_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Owner first name'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='contact_last_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Owner last name'),
        ),
    ]
