# Generated by Django 2.2.12 on 2020-07-09 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0084_auto_20200611_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='contact_first_name',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='contact_last_name',
        ),
    ]
