# Generated by Django 2.2.16 on 2020-09-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0085_auto_20200709_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountstatements',
            name='type',
            field=models.CharField(choices=[('account', 'Account statement - Fio Banka'), ('account_cs', 'Account statement - Česká spořitelna'), ('account_kb', 'Account statement - Komerční Banka'), ('account_csob', 'Account statement - ČSOB'), ('account_sberbank', 'Account statement - Sberbank'), ('account_raiffeisenbank', 'Account statement - Raiffeisenbank '), ('darujme', 'Darujme.cz')], max_length=30),
        ),
    ]
