# Generated by Django 2.2.16 on 2020-09-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0086_auto_20200911_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorpaymentchannel',
            name='regular_frequency',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quaterly', 'Quaterly'), ('biannually', 'Bianually'), ('annually', 'Anually'), (None, '---')], max_length=20, null=True, verbose_name='Frequency of regular payments'),
        ),
    ]
