# Generated by Django 2.2.16 on 2020-10-10 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0081_merge_20200706_0437'),
        ('aklub', '0087_auto_20200918_1159'),
    ]

    operations = [
    ]
