# Generated by Django 2.2.16 on 2020-12-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0087_auto_20200918_1159'),
    ]

    def delete_unused_emails(apps, schema_editor):
        """
        Delete unused profileemails (which has duplicity emails)
        """
        ProfileEmail = apps.get_model('aklub', 'ProfileEmail')
        ProfileEmail.objects.filter(user__isnull=True).delete()

    operations = [
        migrations.RunPython(delete_unused_emails, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='profileemail',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
