# Generated by Django 2.2.16 on 2020-12-04 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0087_auto_20200918_1159'),
    ]
    def delete_unused_emails(apps, schema_editor):
        """
        Delete unused profileemails (which has duplicity emails)
        """
        ProfileEmail = apps.get_model('aklub', 'ProfileEmail')
        ProfileEmail.objects.filter(user__isnull=True).delete()

    operations = [
        migrations.RunPython(delete_unused_emails, reverse_code=migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='administrativeunit',
            options={'verbose_name': 'Administrative unit', 'verbose_name_plural': 'Administrative units'},
        ),
        migrations.AlterModelOptions(
            name='apiaccount',
            options={'verbose_name': 'Api Account', 'verbose_name_plural': 'Api Accounts'},
        ),
        migrations.AlterModelOptions(
            name='companycontact',
            options={'verbose_name': 'Company contact', 'verbose_name_plural': 'Company contacts'},
        ),
        migrations.AlterModelOptions(
            name='moneyaccount',
            options={'verbose_name': 'Bank/Api account', 'verbose_name_plural': 'Bank/Api accounts'},
        ),
        migrations.AlterModelOptions(
            name='preference',
            options={'verbose_name': 'Preference', 'verbose_name_plural': 'Preferences'},
        ),
        migrations.AlterField(
            model_name='accountstatements',
            name='csv_file',
            field=models.FileField(upload_to='account-statements', verbose_name='csv file'),
        ),
        migrations.AlterField(
            model_name='accountstatements',
            name='date_from',
            field=models.DateField(blank=True, null=True, verbose_name='Date from'),
        ),
        migrations.AlterField(
            model_name='accountstatements',
            name='date_to',
            field=models.DateField(blank=True, null=True, verbose_name='Date to'),
        ),
        migrations.AlterField(
            model_name='accountstatements',
            name='import_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Import date'),
        ),
        migrations.AlterField(
            model_name='accountstatements',
            name='type',
            field=models.CharField(choices=[('account', 'Account statement - Fio Banka'), ('account_cs', 'Account statement - Česká spořitelna'), ('account_kb', 'Account statement - Komerční Banka'), ('account_csob', 'Account statement - ČSOB'), ('account_sberbank', 'Account statement - Sberbank'), ('account_raiffeisenbank', 'Account statement - Raiffeisenbank '), ('darujme', 'Darujme.cz')], max_length=30, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='automaticcommunication',
            name='method_type',
            field=models.ForeignKey(help_text='Interaction type with allowed sending', limit_choices_to=models.Q(('send_sms', True), ('send_email', True), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='interactions.InteractionType', verbose_name='Method/Type of Interaction'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_account',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bank Account'),
        ),
        migrations.AlterField(
            model_name='donorpaymentchannel',
            name='money_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moneyaccounts', to='aklub.MoneyAccount', verbose_name='Bank/Api account'),
        ),
        migrations.AlterField(
            model_name='donorpaymentchannel',
            name='regular_frequency',
            field=models.CharField(blank=True, choices=[(None, '---'), ('monthly', 'Monthly'), ('quaterly', 'Quaterly'), ('biannually', 'Bianually'), ('annually', 'Anually')], max_length=20, null=True, verbose_name='Frequency of regular payments'),
        ),
        migrations.AlterField(
            model_name='donorpaymentchannel',
            name='user_bank_account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userbankaccounts', to='aklub.UserBankAccount', verbose_name='User bank account'),
        ),
        migrations.AlterField(
            model_name='masscommunication',
            name='method_type',
            field=models.ForeignKey(help_text='Interaction type with allowed sending', limit_choices_to=models.Q(('send_sms', True), ('send_email', True), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='interactions.InteractionType', verbose_name='Method/Type of Interaction'),
        ),
        migrations.AlterField(
            model_name='profileemail',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True, verbose_name='email address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taxconfirmation',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='taxconfirmation',
            name='pdf_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smmapdfs.PdfSandwichType', verbose_name='PDF type'),
        ),
        migrations.AlterField(
            model_name='taxconfirmation',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Year'),
        ),
    ]
