# Generated by Django 2.2.16 on 2020-11-11 13:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0087_auto_20200918_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automaticcommunication',
            name='sent_to_users',
            field=models.ManyToManyField(blank=True, help_text='List of users to whom this communication was already sent', to=settings.AUTH_USER_MODEL),
        ),
    ]
