# Generated by Django 2.2.17 on 2020-12-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0088_auto_20201204_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativeunit',
            name='from_email_address',
            field=models.EmailField(default='example@nothing_will_sent.ex', help_text='Every new address has to be set up by system administrator', max_length=254, verbose_name='E-mail from address'),
        ),
        migrations.AlterField(
            model_name='administrativeunit',
            name='from_email_str',
            field=models.CharField(default='Example <example@nothing_will_sent.ex>', max_length=255, verbose_name='E-mail from identifier'),
        ),
    ]
