# Generated by Django 2.2.16 on 2020-11-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0088_auto_20201111_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativeunit',
            name='slug',
            field=models.SlugField(blank=True, default=None, help_text='Identifier of the administrative unit', max_length=100, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
