# Generated by Django 2.2.17 on 2020-12-10 10:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0089_auto_20201209_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='created',
            new_name='date_from',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='terminated',
            new_name='date_to',
        ),
        migrations.AlterField(
            model_name='event',
            name='variable_symbol_prefix',
            field=models.PositiveIntegerField(help_text='Number between 10000-99999', null=True, validators=[django.core.validators.MinValueValidator(10000), django.core.validators.MaxValueValidator(99999)], verbose_name='Variable_symbol_prefix'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_from',
            field=models.DateField(blank=True, null=True, verbose_name='Date from'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_to',
            field=models.DateField(blank=True, null=True, verbose_name='Date to'),
        ),
        migrations.AlterField(
            model_name='event',
            name='email_confirmation_redirect',
            field=models.URLField(blank=True, null=True, verbose_name='Redirect to url after email confirmation'),
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of event type', max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Description of this type', max_length=3000, verbose_name='Description')),
            ],
        ),
        migrations.AlterModelOptions(
            name='eventtype',
            options={'verbose_name': 'Event type', 'verbose_name_plural': 'Event types'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='acquisition_campaign',
        ),
        migrations.AddField(
            model_name='event',
            name='age_from',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Age from'),
        ),
        migrations.AddField(
            model_name='event',
            name='age_to',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Age to'),
        ),
        migrations.AddField(
            model_name='event',
            name='basic_purpose',
            field=models.CharField(choices=[('action', 'Action'), ('petition', 'Petition'), ('camp', 'Camp')], default='action', max_length=128, verbose_name='Basic Purpose'),
        ),
        migrations.AddField(
            model_name='event',
            name='entry_form_url',
            field=models.URLField(blank=True, null=True, verbose_name='Url address of register form'),
        ),
        migrations.AddField(
            model_name='event',
            name='focus_on_members',
            field=models.BooleanField(default=False, verbose_name='Focus on members'),
        ),
        migrations.AddField(
            model_name='event',
            name='grant',
            field=models.CharField(choices=[('no_grant', 'No Grant'), ('MEYS', 'Ministry of Education, Youth and Sports'), ('others', 'Others')], default='no_grant', max_length=128, verbose_name='Grant'),
        ),
        migrations.AddField(
            model_name='event',
            name='indended_for',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('adolescents_and_adults', 'Adolescents and adults'), ('children', 'Children'), ('parents_and_children', 'Parents and children'), ('newcomers', 'Newcomers')], default='everyone', max_length=128, verbose_name='Indended for'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_internal',
            field=models.BooleanField(default=False, verbose_name='Only for internal members'),
        ),
        migrations.AddField(
            model_name='event',
            name='meeting',
            field=models.CharField(blank=True, max_length=128, verbose_name='Meeting at the event'),
        ),
        migrations.AddField(
            model_name='event',
            name='note',
            field=models.TextField(blank=True, help_text='Note of this campaign', max_length=3000, verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='event',
            name='participation_fee',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Participation fee'),
        ),
        migrations.AddField(
            model_name='event',
            name='program',
            field=models.CharField(blank=True, choices=[('', '---'), ('education', 'Education'), ('PsB', 'PsB'), ('monuments', 'Monuments'), ('nature', 'Nature'), ('eco_consulting', 'Eco consulting'), ('children_section ', "Children's Section")], default='', max_length=128, verbose_name='Program'),
        ),
        migrations.AddField(
            model_name='event',
            name='public_on_web',
            field=models.BooleanField(default=False, verbose_name='Public on webpage'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='aklub.EventType', verbose_name='Event type'),
        ),
    ]
