# Generated by Django 2.2.16 on 2020-11-11 13:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0090_auto_20201210_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automaticcommunication',
            name='sent_to_users',
            field=models.ManyToManyField(blank=True, help_text='List of users to whom this communication was already sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='administrativeunit',
            name='slug',
            field=models.SlugField(blank=True, default=None, help_text='Identifier of the administrative unit', max_length=100, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
