# Generated by Django 2.2.18 on 2021-02-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0091_auto_20201111_1403'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table='events_event',
        ),
        migrations.AlterModelTable(
            name='eventtype',
            table='events_eventtype',
        ),
    ]
