# Generated by Django 2.2.18 on 2021-02-11 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0012_auto_20210211_1311'),
        ('aklub', '0093_auto_20210211_1251'),
        ('events', "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiaccount',
            name='event',
            field=models.ForeignKey(help_text='Event', on_delete=django.db.models.deletion.CASCADE, to='events.Event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='automaticcommunication',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Event', null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.Event', verbose_name='Event from which are DonorPaymentChannel data selected'),
        ),
        migrations.AlterField(
            model_name='donorpaymentchannel',
            name='event',
            field=models.ForeignKey(help_text='Event', null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='events.Event', verbose_name='campaign'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='campaigns',
            field=models.ManyToManyField(blank=True, help_text='Associated campaigns', to='events.Event'),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='campaigns',
            field=models.ManyToManyField(blank=True, help_text='Associated campaigns', to='events.Event'),
        ),
        migrations.AlterField(
            model_name='userincampaign',
            name='campaign',
            field=models.ForeignKey(default=None, help_text='Campaign', on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventType',
        ),
    ]
