# Generated by Django 2.2.18 on 2021-02-26 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0095_auto_20210211_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='masscommunication',
            name='status',
            field=models.CharField(blank=True, choices=[('waiting_for_sent', 'Waiting for sent'), ('already_sent', 'Already sent'), ('unknown', 'Unknown')], default='unknown', help_text='have emails already been sent?', max_length=128, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='donorpaymentchannel',
            name='event',
            field=models.ForeignKey(help_text='Event', on_delete=django.db.models.deletion.CASCADE, to='events.Event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='masscommunication',
            name='status',
            field=models.CharField(blank=True, choices=[('waiting_for_sent', 'Waiting for sent'), ('already_sent', 'Already sent'), ('unknown', 'Unknown')], default='waiting_for_sent', help_text='have emails already been sent?', max_length=128, verbose_name='status'),
        ),
    ]
