# Generated by Django 2.2.18 on 2021-03-05 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0096_auto_20210226_1700'),
    ]
    def delete_unused_telephones(apps, schema_editor):
        """
        Delete unused profileemails (which has duplicity emails)
        """
        Telephone = apps.get_model('aklub', 'Telephone')
        Telephone.objects.filter(user__isnull=True).delete()
    operations = [
        migrations.RunPython(delete_unused_telephones, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='telephone',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aklub.UserProfile'),
        ),
    ]
