# Generated by Django 2.2.19 on 2021-03-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0097_auto_20210305_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiaccount',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is the project active', verbose_name='Active'),
        ),
    ]
