# Generated by Django 2.2.19 on 2021-04-01 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0098_apiaccount_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInCampaign',
        ),
    ]
