# Generated by Django 2.2.19 on 2021-04-07 08:48

from django.db import migrations


class Migration(migrations.Migration):
    """
    Recreating Newuser (Proxy model) cause Django do not handle rename of this model...
    There is issue, where proxymodel was inherited from UserInCampaign before (and still is)
    We need to remove and add again this model (to allow delete UserInCampaign)
    """

    dependencies = [
        ('aklub', '0098_apiaccount_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewUser',
        ),
        migrations.DeleteModel(
            name='UserInCampaign',
        ),
        migrations.CreateModel(
            name='NewUser',
            fields=[
            ],
            options={
                'verbose_name': 'new user',
                'verbose_name_plural': 'new users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('aklub.donorpaymentchannel',),
        ),
    ]
