# Generated by Django 2.2.19 on 2021-04-16 14:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0100_auto_20210416_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativeunit',
            name='city',
            field=models.CharField(blank=True, max_length=40, verbose_name='City/City part'),
        ),
        migrations.AddField(
            model_name='administrativeunit',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='au_manager', to='aklub.UserProfile', verbose_name='Manager'),
        ),
        migrations.AddField(
            model_name='administrativeunit',
            name='president',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='au_president', to='aklub.UserProfile', verbose_name='President'),
        ),
        migrations.AddField(
            model_name='administrativeunit',
            name='street',
            field=models.CharField(blank=True, max_length=80, verbose_name='Street and number'),
        ),
        migrations.AddField(
            model_name='administrativeunit',
            name='telephone',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator('^\\+?(42(0|1){1})?\\s?\\d{3}\\s?\\d{3}\\s?\\d{3}$', 'Telephone must consist of numbers, spaces and + sign or maximum number count is higher.')], verbose_name='Telephone number'),
        ),
        migrations.AddField(
            model_name='administrativeunit',
            name='web_url',
            field=models.URLField(blank=True, null=True, verbose_name='Url address of website'),
        ),
        migrations.AddField(
            model_name='administrativeunit',
            name='zip_code',
            field=models.CharField(blank=True, max_length=30, verbose_name='ZIP Code'),
        ),
        migrations.AddField(
            model_name='administrativeunit',
            name='gps_latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='GPS latitude'),
        ),
        migrations.AddField(
            model_name='administrativeunit',
            name='gps_longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='GPS longitude'),
        ),
        migrations.AddField(
            model_name='administrativeunit',
            name='manager_since',
            field=models.DateField(blank=True, null=True, verbose_name='Manager since'),
        ),
        migrations.AddField(
            model_name='administrativeunit',
            name='president_since',
            field=models.DateField(blank=True, null=True, verbose_name='President since'),
        ),
        migrations.AddField(
            model_name='administrativeunit',
            name='level',
            field=models.CharField(blank=True, choices=[('regional_center', 'Regional center'), ('basic_section', 'Basic section'), ('headquarter', 'Headquarter')], max_length=128),
        ),
    ]
