# Generated by Django 2.2.20 on 2021-04-29 16:35

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0101_auto_20210416_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativeunit',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, help_text='Identifier of the administrative unit', max_length=100, null=True, populate_from='name', unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='moneyaccount',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, help_text='Identifier of the Account', max_length=100, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='source',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, help_text='Identifier of the source', max_length=100, populate_from='name', verbose_name='Slug'),
        ),
    ]
