# Generated by Django 2.2.20 on 2021-04-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0102_auto_20210429_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativeunit',
            name='street',
            field=models.CharField(blank=True, max_length=128, verbose_name='Street and number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='correspondence_street',
            field=models.CharField(blank=True, max_length=128, verbose_name='Street and number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='street',
            field=models.CharField(blank=True, max_length=128, verbose_name='Street and number'),
        ),
    ]
