# Generated by Django 2.2.20 on 2021-05-14 05:51

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0103_auto_20210430_1615'),
    ]

    def set_null_preference_to_null(apps, schema_editor):
        Preference = apps.get_model('aklub', 'Preference')
        is_null_user= Preference.objects.filter(user__isnull=True)
        is_null_user.delete()

        call_pref = Preference.objects.filter(call_on__isnull=True)
        call_pref.update(call_on=True)

        newsletter_pref = Preference.objects.filter(newsletter_on__isnull=True)
        newsletter_pref.update(newsletter_on=True)

        challenge_pref = Preference.objects.filter(challenge_on__isnull=True)
        challenge_pref.update(challenge_on=True)

        letter_pref = Preference.objects.filter(letter_on__isnull=True)
        letter_pref.update(letter_on=True)

    operations = [
        migrations.RunPython(set_null_preference_to_null, reverse_code=migrations.RunPython.noop),
    ]
