# Generated by Django 2.2.20 on 2021-05-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0103_auto_20210430_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='maiden_name',
            field=models.CharField(blank=True, max_length=126, verbose_name='Maiden name'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(blank=True, max_length=126, verbose_name='Nickname'),
        ),
    ]
