# Generated by Django 2.2.20 on 2021-05-14 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0104_auto_20210514_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='preference',
            name='call_on',
            field=models.BooleanField(blank=True, default=True, verbose_name='call_on'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='challenge_on',
            field=models.BooleanField(default=True, verbose_name='challenge_on'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='letter_on',
            field=models.BooleanField(default=True, verbose_name='letter_on'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='newsletter_on',
            field=models.BooleanField(default=True, verbose_name='newsletter_on'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Publish my name in the list of supporters'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='send_mailing_lists',
            field=models.BooleanField(default=True, verbose_name='Sending of mailing lists allowed'),
        ),
    ]
