# Generated by Django 2.2.20 on 2021-05-31 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0104_auto_20210519_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativeunit',
            name='level',
            field=models.CharField(choices=[('regional_center', 'Regional center'), ('basic_section', 'Basic section'), ('headquarter', 'Headquarter'), ('club', 'Club')], default='club', max_length=128),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='last name'),
        ),
    ]
