# Generated by Django 2.2.24 on 2021-07-17 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0106_auto_20210704_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='main_entity_or_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_entity_or_club', to='aklub.AdministrativeUnit'),
        ),
        migrations.AddField(
            model_name='payment',
            name='regional_centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regional_centre', to='aklub.AdministrativeUnit'),
        ),
    ]
