# Generated by Django 2.2.24 on 2021-07-27 19:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0106_auto_20210704_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='custom_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
