# Generated by Django 2.2.24 on 2021-07-07 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0106_auto_20210704_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='main_entity_or_club',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Main entity or club'),
        ),
        migrations.AddField(
            model_name='payment',
            name='regional_centre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Regional centre'),
        ),
    ]
